# ----- Impostazioni specifiche per Linux -----

if(CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(${CMAKE_C_COMPILER_VERSION} VERSION_GREATER "14" AND ${CMAKE_C_COMPILER_VERSION} VERSION_LESS "15")
        set(GCC_C_MAJOR_VERSION "14")
    elseif(${CMAKE_C_COMPILER_VERSION} VERSION_GREATER "13" AND ${CMAKE_C_COMPILER_VERSION} VERSION_LESS "14")
        set(GCC_C_MAJOR_VERSION "13")
    elseif(${CMAKE_C_COMPILER_VERSION} VERSION_GREATER "12" AND ${CMAKE_C_COMPILER_VERSION} VERSION_LESS "13")
        set(GCC_C_MAJOR_VERSION "12")
    else()
        message(FATAL_ERROR "La versione ${CMAKE_C_COMPILER_VERSION} di GCC non è supportata.")
    endif()

    if(${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "14" AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS "15")
        set(GCC_CXX_MAJOR_VERSION "14")
    elseif(${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "13" AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS "14")
        set(GCC_CXX_MAJOR_VERSION "13")
    elseif(${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "12" AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS "13")
        set(GCC_CXX_MAJOR_VERSION "12")
    else()
        message(FATAL_ERROR "La versione ${CMAKE_CXX_COMPILER_VERSION} di G++ non è supportata.")
    endif()

    if(NOT ${GCC_C_MAJOR_VERSION} EQUAL ${GCC_CXX_MAJOR_VERSION})
        message(FATAL_ERROR "Le versioni major dei compilatori C e C++ non sono uguali.")
    else()
        set(GCC_MAJOR_VERSION "${GCC_CXX_MAJOR_VERSION}")
    endif()

    include(CMake/Compilatori/GCC/Funzioni.cmake)
    include(CMake/Compilatori/GCC/Impostazioni.cmake)
else()
    if(CMAKE_C_COMPILER_ID STREQUAL CMAKE_CXX_COMPILER_ID)
        message(FATAL_ERROR "Il compilatore C/C++ ${CMAKE_CXX_COMPILER_ID} non è supportato.")
    else()
        message(FATAL_ERROR "I compilatori C ${CMAKE_C_COMPILER_ID} e C++ ${CMAKE_CXX_COMPILER_ID} non sono supportati.")
    endif()
endif()
