#pragma once

namespace Fonts
{
    constexpr char ICON_AD[]     = "\xEE\x80\x83"; // U+E003 Andorra
    constexpr char ICON_AE[]     = "\xEE\x80\x84"; // U+E004 United Arab Emirates
    constexpr char ICON_AF[]     = "\xEE\x80\x85"; // U+E005 Afghanistan
    constexpr char ICON_AG[]     = "\xEE\x80\x86"; // U+E006 Antigua & Barbuda
    constexpr char ICON_AI[]     = "\xEE\x80\x88"; // U+E008 Anguilla
    constexpr char ICON_AL[]     = "\xEE\x80\x8B"; // U+E00B Albania
    constexpr char ICON_AM[]     = "\xEE\x80\x8C"; // U+E00C Armenia
    constexpr char ICON_AO[]     = "\xEE\x80\x8E"; // U+E00E Angola
    constexpr char ICON_AQ[]     = "\xEE\x80\x90"; // U+E010 Antarctica
    constexpr char ICON_AR[]     = "\xEE\x80\x91"; // U+E011 Argentina
    constexpr char ICON_AS[]     = "\xEE\x80\x92"; // U+E012 American Samoa
    constexpr char ICON_AT[]     = "\xEE\x80\x93"; // U+E013 Austria
    constexpr char ICON_AU[]     = "\xEE\x80\x94"; // U+E014 Australia
    constexpr char ICON_AW[]     = "\xEE\x80\x96"; // U+E016 Aruba
    constexpr char ICON_AX[]     = "\xEE\x80\x97"; // U+E017 Åland Islands
    constexpr char ICON_AZ[]     = "\xEE\x80\x99"; // U+E019 Azerbaijan
    constexpr char ICON_BA[]     = "\xEE\x80\x9A"; // U+E01A Bosnia & Herzegovina
    constexpr char ICON_BB[]     = "\xEE\x80\x9B"; // U+E01B Barbados
    constexpr char ICON_BD[]     = "\xEE\x80\x9D"; // U+E01D Bangladesh
    constexpr char ICON_BE[]     = "\xEE\x80\x9E"; // U+E01E Belgium
    constexpr char ICON_BF[]     = "\xEE\x80\x9F"; // U+E01F Burkina Faso
    constexpr char ICON_BG[]     = "\xEE\x80\xA0"; // U+E020 Bulgaria
    constexpr char ICON_BH[]     = "\xEE\x80\xA1"; // U+E021 Bahrain
    constexpr char ICON_BI[]     = "\xEE\x80\xA2"; // U+E022 Burundi
    constexpr char ICON_BJ[]     = "\xEE\x80\xA3"; // U+E023 Benin
    constexpr char ICON_BL[]     = "\xEE\x80\xA5"; // U+E025 St. Barthélemy
    constexpr char ICON_BM[]     = "\xEE\x80\xA6"; // U+E026 Bermuda
    constexpr char ICON_BN[]     = "\xEE\x80\xA7"; // U+E027 Brunei
    constexpr char ICON_BO[]     = "\xEE\x80\xA8"; // U+E028 Bolivia
    constexpr char ICON_BQ[]     = "\xEE\x80\xAA"; // U+E02A Caribbean Netherlands
    constexpr char ICON_BR[]     = "\xEE\x80\xAB"; // U+E02B Brazil
    constexpr char ICON_BS[]     = "\xEE\x80\xAC"; // U+E02C Bahamas
    constexpr char ICON_BT[]     = "\xEE\x80\xAD"; // U+E02D Bhutan
    constexpr char ICON_BV[]     = "\xEE\x80\xAF"; // U+E02F Bouvet Island
    constexpr char ICON_BW[]     = "\xEE\x80\xB0"; // U+E030 Botswana
    constexpr char ICON_BY[]     = "\xEE\x80\xB2"; // U+E032 Belarus
    constexpr char ICON_BZ[]     = "\xEE\x80\xB3"; // U+E033 Belize
    constexpr char ICON_CA[]     = "\xEE\x80\xB4"; // U+E034 Canada
    constexpr char ICON_CC[]     = "\xEE\x80\xB6"; // U+E036 Cocos (Keeling) Islands
    constexpr char ICON_CD[]     = "\xEE\x80\xB7"; // U+E037 Congo - Kinshasa
    constexpr char ICON_CF[]     = "\xEE\x80\xB9"; // U+E039 Central African Republic
    constexpr char ICON_CG[]     = "\xEE\x80\xBA"; // U+E03A Congo - Brazzaville
    constexpr char ICON_CH[]     = "\xEE\x80\xBB"; // U+E03B Switzerland
    constexpr char ICON_CI[]     = "\xEE\x80\xBC"; // U+E03C Côte d’Ivoire
    constexpr char ICON_CK[]     = "\xEE\x80\xBE"; // U+E03E Cook Islands
    constexpr char ICON_CL[]     = "\xEE\x80\xBF"; // U+E03F Chile
    constexpr char ICON_CM[]     = "\xEE\x81\x80"; // U+E040 Cameroon
    constexpr char ICON_CN[]     = "\xEE\x81\x81"; // U+E041 China
    constexpr char ICON_CO[]     = "\xEE\x81\x82"; // U+E042 Colombia
    constexpr char ICON_CP[]     = "\xEE\x81\x83"; // U+E043 Clipperton Island
    constexpr char ICON_CQ[]     = "\xEE\x81\x84"; // U+E044 Sark
    constexpr char ICON_CR[]     = "\xEE\x81\x85"; // U+E045 Costa Rica
    constexpr char ICON_CS[]     = "\xEE\x81\x86";
    constexpr char ICON_CU[]     = "\xEE\x81\x88"; // U+E048 Cuba
    constexpr char ICON_CV[]     = "\xEE\x81\x89"; // U+E049 Cape Verde
    constexpr char ICON_CW[]     = "\xEE\x81\x8A"; // U+E04A Curaçao
    constexpr char ICON_CX[]     = "\xEE\x81\x8B"; // U+E04B Christmas Island
    constexpr char ICON_CY[]     = "\xEE\x81\x8C"; // U+E04C Cyprus
    constexpr char ICON_CZ[]     = "\xEE\x81\x8D"; // U+E04D Czechia
    constexpr char ICON_DD[]     = "\xEE\x81\x91";
    constexpr char ICON_DE[]     = "\xEE\x81\x92"; // U+E052 Germany
    constexpr char ICON_DJ[]     = "\xEE\x81\x97"; // U+E057 Djibouti
    constexpr char ICON_DK[]     = "\xEE\x81\x98"; // U+E058 Denmark
    constexpr char ICON_DM[]     = "\xEE\x81\x9A"; // U+E05A Dominica
    constexpr char ICON_DO[]     = "\xEE\x81\x9C"; // U+E05C Dominican Republic
    constexpr char ICON_DZ[]     = "\xEE\x81\xA7"; // U+E067 Algeria
    constexpr char ICON_EC[]     = "\xEE\x81\xAA"; // U+E06A Ecuador
    constexpr char ICON_EE[]     = "\xEE\x81\xAC"; // U+E06C Estonia
    constexpr char ICON_EG[]     = "\xEE\x81\xAE"; // U+E06E Egypt
    constexpr char ICON_EH[]     = "\xEE\x81\xAF"; // U+E06F Western Sahara
    constexpr char ICON_ER[]     = "\xEE\x81\xB9"; // U+E079 Eritrea
    constexpr char ICON_ES[]     = "\xEE\x81\xBA"; // U+E07A Spain
    constexpr char ICON_ET[]     = "\xEE\x81\xBB"; // U+E07B Ethiopia
    constexpr char ICON_EU[]     = "\xEE\x81\xBC"; // U+E07C European Union
    constexpr char ICON_FI[]     = "\xEE\x82\x8A"; // U+E08A Finland
    constexpr char ICON_FJ[]     = "\xEE\x82\x8B"; // U+E08B Fiji
    constexpr char ICON_FK[]     = "\xEE\x82\x8C"; // U+E08C Falkland Islands
    constexpr char ICON_FM[]     = "\xEE\x82\x8E"; // U+E08E Micronesia
    constexpr char ICON_FO[]     = "\xEE\x82\x90"; // U+E090 Faroe Islands
    constexpr char ICON_FR[]     = "\xEE\x82\x93"; // U+E093 France
    constexpr char ICON_GA[]     = "\xEE\x82\x9C"; // U+E09C Gabon
    constexpr char ICON_GB[]     = "\xEE\x82\x9D"; // U+E09D United Kingdom
    constexpr char ICON_GD[]     = "\xEE\x82\x9F"; // U+E09F Grenada
    constexpr char ICON_GE[]     = "\xEE\x82\xA0"; // U+E0A0 Georgia
    constexpr char ICON_GF[]     = "\xEE\x82\xA1"; // U+E0A1 French Guiana
    constexpr char ICON_GG[]     = "\xEE\x82\xA2"; // U+E0A2 Guernsey
    constexpr char ICON_GH[]     = "\xEE\x82\xA3"; // U+E0A3 Ghana
    constexpr char ICON_GI[]     = "\xEE\x82\xA4"; // U+E0A4 Gibraltar
    constexpr char ICON_GL[]     = "\xEE\x82\xA7"; // U+E0A7 Greenland
    constexpr char ICON_GM[]     = "\xEE\x82\xA8"; // U+E0A8 Gambia
    constexpr char ICON_GN[]     = "\xEE\x82\xA9"; // U+E0A9 Guinea
    constexpr char ICON_GP[]     = "\xEE\x82\xAB"; // U+E0AB Guadeloupe
    constexpr char ICON_GQ[]     = "\xEE\x82\xAC"; // U+E0AC Equatorial Guinea
    constexpr char ICON_GR[]     = "\xEE\x82\xAD"; // U+E0AD Greece
    constexpr char ICON_GS[]     = "\xEE\x82\xAE"; // U+E0AE South Georgia & South Sandwich Islands
    constexpr char ICON_GT[]     = "\xEE\x82\xAF"; // U+E0AF Guatemala
    constexpr char ICON_GU[]     = "\xEE\x82\xB0"; // U+E0B0 Guam
    constexpr char ICON_GW[]     = "\xEE\x82\xB2"; // U+E0B2 Guinea-Bissau
    constexpr char ICON_GY[]     = "\xEE\x82\xB4"; // U+E0B4 Guyana
    constexpr char ICON_HK[]     = "\xEE\x83\x80"; // U+E0C0 Hong Kong SAR China
    constexpr char ICON_HM[]     = "\xEE\x83\x82"; // U+E0C2 Heard & McDonald Islands
    constexpr char ICON_HN[]     = "\xEE\x83\x83"; // U+E0C3 Honduras
    constexpr char ICON_HR[]     = "\xEE\x83\x87"; // U+E0C7 Croatia
    constexpr char ICON_HT[]     = "\xEE\x83\x89"; // U+E0C9 Haiti
    constexpr char ICON_HU[]     = "\xEE\x83\x8A"; // U+E0CA Hungary
    constexpr char ICON_ID[]     = "\xEE\x83\x93"; // U+E0D3 Indonesia
    constexpr char ICON_IE[]     = "\xEE\x83\x94"; // U+E0D4 Ireland
    constexpr char ICON_IL[]     = "\xEE\x83\x9B"; // U+E0DB Israel
    constexpr char ICON_IM[]     = "\xEE\x83\x9C"; // U+E0DC Isle of Man
    constexpr char ICON_IN[]     = "\xEE\x83\x9D"; // U+E0DD India
    constexpr char ICON_IO[]     = "\xEE\x83\x9E"; // U+E0DE British Indian Ocean Territory
    constexpr char ICON_IQ[]     = "\xEE\x83\xA0"; // U+E0E0 Iraq
    constexpr char ICON_IR[]     = "\xEE\x83\xA1"; // U+E0E1 Iran
    constexpr char ICON_IS[]     = "\xEE\x83\xA2"; // U+E0E2 Iceland
    constexpr char ICON_IT[]     = "\xEE\x83\xA3"; // U+E0E3 Italy
    constexpr char ICON_JE[]     = "\xEE\x83\xAE"; // U+E0EE Jersey
    constexpr char ICON_JM[]     = "\xEE\x83\xB6"; // U+E0F6 Jamaica
    constexpr char ICON_JO[]     = "\xEE\x83\xB8"; // U+E0F8 Jordan
    constexpr char ICON_JP[]     = "\xEE\x83\xB9"; // U+E0F9 Japan
    constexpr char ICON_KE[]     = "\xEE\x84\x88"; // U+E108 Kenya
    constexpr char ICON_KG[]     = "\xEE\x84\x8A"; // U+E10A Kyrgyzstan
    constexpr char ICON_KH[]     = "\xEE\x84\x8B"; // U+E10B Cambodia
    constexpr char ICON_KI[]     = "\xEE\x84\x8C"; // U+E10C Kiribati
    constexpr char ICON_KM[]     = "\xEE\x84\x90"; // U+E110 Comoros
    constexpr char ICON_KN[]     = "\xEE\x84\x91"; // U+E111 St. Kitts & Nevis
    constexpr char ICON_KP[]     = "\xEE\x84\x93"; // U+E113 North Korea
    constexpr char ICON_KR[]     = "\xEE\x84\x95"; // U+E115 South Korea
    constexpr char ICON_KW[]     = "\xEE\x84\x9A"; // U+E11A Kuwait
    constexpr char ICON_KY[]     = "\xEE\x84\x9C"; // U+E11C Cayman Islands
    constexpr char ICON_KZ[]     = "\xEE\x84\x9D"; // U+E11D Kazakhstan
    constexpr char ICON_LA[]     = "\xEE\x84\x9E"; // U+E11E Laos
    constexpr char ICON_LB[]     = "\xEE\x84\x9F"; // U+E11F Lebanon
    constexpr char ICON_LC[]     = "\xEE\x84\xA0"; // U+E120 St. Lucia
    constexpr char ICON_LI[]     = "\xEE\x84\xA6"; // U+E126 Liechtenstein
    constexpr char ICON_LK[]     = "\xEE\x84\xA8"; // U+E128 Sri Lanka
    constexpr char ICON_LR[]     = "\xEE\x84\xAF"; // U+E12F Liberia
    constexpr char ICON_LS[]     = "\xEE\x84\xB0"; // U+E130 Lesotho
    constexpr char ICON_LT[]     = "\xEE\x84\xB1"; // U+E131 Lithuania
    constexpr char ICON_LU[]     = "\xEE\x84\xB2"; // U+E132 Luxembourg
    constexpr char ICON_LV[]     = "\xEE\x84\xB3"; // U+E133 Latvia
    constexpr char ICON_LY[]     = "\xEE\x84\xB6"; // U+E136 Libya
    constexpr char ICON_MA[]     = "\xEE\x84\xB8"; // U+E138 Morocco
    constexpr char ICON_MC[]     = "\xEE\x84\xBA"; // U+E13A Monaco
    constexpr char ICON_MD[]     = "\xEE\x84\xBB"; // U+E13B Moldova
    constexpr char ICON_ME[]     = "\xEE\x84\xBC"; // U+E13C Montenegro
    constexpr char ICON_MF[]     = "\xEE\x84\xBD"; // U+E13D St. Martin
    constexpr char ICON_MG[]     = "\xEE\x84\xBE"; // U+E13E Madagascar
    constexpr char ICON_MH[]     = "\xEE\x84\xBF"; // U+E13F Marshall Islands
    constexpr char ICON_MK[]     = "\xEE\x85\x82"; // U+E142 North Macedonia
    constexpr char ICON_ML[]     = "\xEE\x85\x83"; // U+E143 Mali
    constexpr char ICON_MM[]     = "\xEE\x85\x84"; // U+E144 Myanmar (Burma)
    constexpr char ICON_MN[]     = "\xEE\x85\x85"; // U+E145 Mongolia
    constexpr char ICON_MO[]     = "\xEE\x85\x86"; // U+E146 Macao SAR China
    constexpr char ICON_MP[]     = "\xEE\x85\x87"; // U+E147 Northern Mariana Islands
    constexpr char ICON_MQ[]     = "\xEE\x85\x88"; // U+E148 Martinique
    constexpr char ICON_MR[]     = "\xEE\x85\x89"; // U+E149 Mauritania
    constexpr char ICON_MS[]     = "\xEE\x85\x8A"; // U+E14A Montserrat
    constexpr char ICON_MT[]     = "\xEE\x85\x8B"; // U+E14B Malta
    constexpr char ICON_MU[]     = "\xEE\x85\x8C"; // U+E14C Mauritius
    constexpr char ICON_MV[]     = "\xEE\x85\x8D"; // U+E14D Maldives
    constexpr char ICON_MW[]     = "\xEE\x85\x8E"; // U+E14E Malawi
    constexpr char ICON_MX[]     = "\xEE\x85\x8F"; // U+E14F Mexico
    constexpr char ICON_MY[]     = "\xEE\x85\x90"; // U+E150 Malaysia
    constexpr char ICON_MZ[]     = "\xEE\x85\x91"; // U+E151 Mozambique
    constexpr char ICON_NA[]     = "\xEE\x85\x92"; // U+E152 Namibia
    constexpr char ICON_NC[]     = "\xEE\x85\x94"; // U+E154 New Caledonia
    constexpr char ICON_NE[]     = "\xEE\x85\x96"; // U+E156 Niger
    constexpr char ICON_NF[]     = "\xEE\x85\x97"; // U+E157 Norfolk Island
    constexpr char ICON_NG[]     = "\xEE\x85\x98"; // U+E158 Nigeria
    constexpr char ICON_NI[]     = "\xEE\x85\x9A"; // U+E15A Nicaragua
    constexpr char ICON_NL[]     = "\xEE\x85\x9D"; // U+E15D Netherlands
    constexpr char ICON_NO[]     = "\xEE\x85\xA0"; // U+E160 Norway
    constexpr char ICON_NP[]     = "\xEE\x85\xA1"; // U+E161 Nepal
    constexpr char ICON_NR[]     = "\xEE\x85\xA3"; // U+E163 Nauru
    constexpr char ICON_NU[]     = "\xEE\x85\xA6"; // U+E166 Niue
    constexpr char ICON_NZ[]     = "\xEE\x85\xAB"; // U+E16B New Zealand
    constexpr char ICON_OM[]     = "\xEE\x85\xB8"; // U+E178 Oman
    constexpr char ICON_PA[]     = "\xEE\x86\x86"; // U+E186 Panama
    constexpr char ICON_PE[]     = "\xEE\x86\x8A"; // U+E18A Peru
    constexpr char ICON_PF[]     = "\xEE\x86\x8B"; // U+E18B French Polynesia
    constexpr char ICON_PG[]     = "\xEE\x86\x8C"; // U+E18C Papua New Guinea
    constexpr char ICON_PH[]     = "\xEE\x86\x8D"; // U+E18D Philippines
    constexpr char ICON_PK[]     = "\xEE\x86\x90"; // U+E190 Pakistan
    constexpr char ICON_PL[]     = "\xEE\x86\x91"; // U+E191 Poland
    constexpr char ICON_PM[]     = "\xEE\x86\x92"; // U+E192 St. Pierre & Miquelon
    constexpr char ICON_PN[]     = "\xEE\x86\x93"; // U+E193 Pitcairn Islands
    constexpr char ICON_PR[]     = "\xEE\x86\x97"; // U+E197 Puerto Rico
    constexpr char ICON_PS[]     = "\xEE\x86\x98"; // U+E198 Palestinian Territories
    constexpr char ICON_PT[]     = "\xEE\x86\x99"; // U+E199 Portugal
    constexpr char ICON_PW[]     = "\xEE\x86\x9C"; // U+E19C Palau
    constexpr char ICON_PY[]     = "\xEE\x86\x9E"; // U+E19E Paraguay
    constexpr char ICON_QA[]     = "\xEE\x86\xA0"; // U+E1A0 Qatar
    constexpr char ICON_RE[]     = "\xEE\x86\xBE"; // U+E1BE Réunion
    constexpr char ICON_RO[]     = "\xEE\x87\x88"; // U+E1C8 Romania
    constexpr char ICON_RS[]     = "\xEE\x87\x8C"; // U+E1CC Serbia
    constexpr char ICON_RU[]     = "\xEE\x87\x8E"; // U+E1CE Russia
    constexpr char ICON_RW[]     = "\xEE\x87\x90"; // U+E1D0 Rwanda
    constexpr char ICON_SA[]     = "\xEE\x87\x94"; // U+E1D4 Saudi Arabia
    constexpr char ICON_SB[]     = "\xEE\x87\x95"; // U+E1D5 Solomon Islands
    constexpr char ICON_SC[]     = "\xEE\x87\x96"; // U+E1D6 Seychelles
    constexpr char ICON_SD[]     = "\xEE\x87\x97"; // U+E1D7 Sudan
    constexpr char ICON_SE[]     = "\xEE\x87\x98"; // U+E1D8 Sweden
    constexpr char ICON_SG[]     = "\xEE\x87\x9A"; // U+E1DA Singapore
    constexpr char ICON_SH[]     = "\xEE\x87\x9B"; // U+E1DB St. Helena
    constexpr char ICON_SI[]     = "\xEE\x87\x9C"; // U+E1DC Slovenia
    constexpr char ICON_SJ[]     = "\xEE\x87\x9D"; // U+E1DD Svalbard & Jan Mayen
    constexpr char ICON_SK[]     = "\xEE\x87\x9E"; // U+E1DE Slovakia
    constexpr char ICON_SL[]     = "\xEE\x87\x9F"; // U+E1DF Sierra Leone
    constexpr char ICON_SM[]     = "\xEE\x87\xA0"; // U+E1E0 San Marino
    constexpr char ICON_SN[]     = "\xEE\x87\xA1"; // U+E1E1 Senegal
    constexpr char ICON_SO[]     = "\xEE\x87\xA2"; // U+E1E2 Somalia
    constexpr char ICON_SR[]     = "\xEE\x87\xA5"; // U+E1E5 Suriname
    constexpr char ICON_SS[]     = "\xEE\x87\xA6"; // U+E1E6 South Sudan
    constexpr char ICON_ST[]     = "\xEE\x87\xA7"; // U+E1E7 São Tomé & Príncipe
    constexpr char ICON_SU[]     = "\xEE\x87\xA8";
    constexpr char ICON_SV[]     = "\xEE\x87\xA9"; // U+E1E9 El Salvador
    constexpr char ICON_SX[]     = "\xEE\x87\xAB"; // U+E1EB Sint Maarten
    constexpr char ICON_SY[]     = "\xEE\x87\xAC"; // U+E1EC Syria
    constexpr char ICON_SZ[]     = "\xEE\x87\xAD"; // U+E1ED Eswatini
    constexpr char ICON_TC[]     = "\xEE\x87\xB0"; // U+E1F0 Turks & Caicos Islands
    constexpr char ICON_TD[]     = "\xEE\x87\xB1"; // U+E1F1 Chad
    constexpr char ICON_TF[]     = "\xEE\x87\xB3"; // U+E1F3 French Southern Territories
    constexpr char ICON_TG[]     = "\xEE\x87\xB4"; // U+E1F4 Togo
    constexpr char ICON_TH[]     = "\xEE\x87\xB5"; // U+E1F5 Thailand
    constexpr char ICON_TJ[]     = "\xEE\x87\xB7"; // U+E1F7 Tajikistan
    constexpr char ICON_TK[]     = "\xEE\x87\xB8"; // U+E1F8 Tokelau
    constexpr char ICON_TL[]     = "\xEE\x87\xB9"; // U+E1F9 Timor-Leste
    constexpr char ICON_TM[]     = "\xEE\x87\xBA"; // U+E1FA Turkmenistan
    constexpr char ICON_TN[]     = "\xEE\x87\xBB"; // U+E1FB Tunisia
    constexpr char ICON_TO[]     = "\xEE\x87\xBC"; // U+E1FC Tonga
    constexpr char ICON_TR[]     = "\xEE\x87\xBF"; // U+E1FF Türkiye
    constexpr char ICON_TT[]     = "\xEE\x88\x81"; // U+E201 Trinidad & Tobago
    constexpr char ICON_TV[]     = "\xEE\x88\x83"; // U+E203 Tuvalu
    constexpr char ICON_TW[]     = "\xEE\x88\x84"; // U+E204 Taiwan
    constexpr char ICON_TZ[]     = "\xEE\x88\x87"; // U+E207 Tanzania
    constexpr char ICON_UA[]     = "\xEE\x88\x88"; // U+E208 Ukraine
    constexpr char ICON_UG[]     = "\xEE\x88\x8E"; // U+E20E Uganda
    constexpr char ICON_UM[]     = "\xEE\x88\x94"; // U+E214 U.S. Outlying Islands
    constexpr char ICON_UN[]     = "\xEE\x88\x95"; // U+E215 United Nations
    constexpr char ICON_US[]     = "\xEE\x88\x9A"; // U+E21A United States
    constexpr char ICON_UY[]     = "\xEE\x88\xA0"; // U+E220 Uruguay
    constexpr char ICON_UZ[]     = "\xEE\x88\xA1"; // U+E221 Uzbekistan
    constexpr char ICON_VA[]     = "\xEE\x88\xA2"; // U+E222 Vatican City
    constexpr char ICON_VC[]     = "\xEE\x88\xA4"; // U+E224 St. Vincent & Grenadines
    constexpr char ICON_VE[]     = "\xEE\x88\xA6"; // U+E226 Venezuela
    constexpr char ICON_VG[]     = "\xEE\x88\xA8"; // U+E228 British Virgin Islands
    constexpr char ICON_VI[]     = "\xEE\x88\xAA"; // U+E22A U.S. Virgin Islands
    constexpr char ICON_VN[]     = "\xEE\x88\xAF"; // U+E22F Vietnam
    constexpr char ICON_VU[]     = "\xEE\x88\xB6"; // U+E236 Vanuatu
    constexpr char ICON_WF[]     = "\xEE\x89\x81"; // U+E241 Wallis & Futuna
    constexpr char ICON_WS[]     = "\xEE\x89\x8E"; // U+E24E Samoa
    constexpr char ICON_XK[]     = "\xEE\x89\xA0"; // U+E260 Kosovo
    constexpr char ICON_YE[]     = "\xEE\x89\xB4"; // U+E274 Yemen
    constexpr char ICON_YT[]     = "\xEE\x8A\x83"; // U+E283 Mayotte
    constexpr char ICON_YU[]     = "\xEE\x8A\x84";
    constexpr char ICON_ZA[]     = "\xEE\x8A\x8A"; // U+E28A South Africa
    constexpr char ICON_ZM[]     = "\xEE\x8A\x96"; // U+E296 Zambia
    constexpr char ICON_ZW[]     = "\xEE\x8A\xA0"; // U+E2A0 Zimbabwe
    constexpr char ICON_MR_OLD[] = "\xEE\x8A\xB0";
    constexpr char ICON_HN_OLD[] = "\xEE\x8A\xB1";
    constexpr char ICON_SY_OLD[] = "\xEE\x8A\xB2";
    constexpr char ICON_AUSTRALIAN_ABORIGINAL_FLAG[] = "\xEE\x8B\x80";
    constexpr char ICON_REFUGEE_NATION_FLAG[]        = "\xEE\x8B\x81";
    constexpr char ICON_PIRATE_FLAG[]                = "\xEE\x8B\xA0";
    constexpr char ICON_RAINBOW_FLAG[]               = "\xEE\x8B\xB0";
    constexpr char ICON_TRANSGENDER_FLAG[]           = "\xEE\x8B\xB1";
    constexpr char ICON_AT_1[]                       = "\xEE\x8C\x80";
    constexpr char ICON_AT_2[]                       = "\xEE\x8C\x81";
    constexpr char ICON_AT_3[]                       = "\xEE\x8C\x82";
    constexpr char ICON_AT_4[]                       = "\xEE\x8C\x83";
    constexpr char ICON_AT_5[]                       = "\xEE\x8C\x84";
    constexpr char ICON_AT_6[]                       = "\xEE\x8C\x85";
    constexpr char ICON_AT_7[]                       = "\xEE\x8C\x86";
    constexpr char ICON_AT_8[]                       = "\xEE\x8C\x87";
    constexpr char ICON_AT_9[]                       = "\xEE\x8C\x88";
    constexpr char ICON_BE_BRU[]                     = "\xEE\x8C\x90";
    constexpr char ICON_BE_VLG[]                     = "\xEE\x8C\x91";
    constexpr char ICON_BE_WAL[]                     = "\xEE\x8C\x92";
    constexpr char ICON_BQ_BO[]                      = "\xEE\x8C\xA0";
    constexpr char ICON_BQ_SA[]                      = "\xEE\x8C\xA1";
    constexpr char ICON_BQ_SE[]                      = "\xEE\x8C\xA2";
    constexpr char ICON_CA_NL[]                      = "\xEE\x8C\xB0";
    constexpr char ICON_CA_NU[]                      = "\xEE\x8C\xB1";
    constexpr char ICON_CA_QC[]                      = "\xEE\x8C\xB2";
    constexpr char ICON_CH_FR[]                      = "\xEE\x8D\x80";
    constexpr char ICON_CH_LU[]                      = "\xEE\x8D\x81";
    constexpr char ICON_CH_NE[]                      = "\xEE\x8D\x82";
    constexpr char ICON_CH_SO[]                      = "\xEE\x8D\x83";
    constexpr char ICON_CH_SZ[]                      = "\xEE\x8D\x84";
    constexpr char ICON_CH_TI[]                      = "\xEE\x8D\x85";
    constexpr char ICON_CH_VS[]                      = "\xEE\x8D\x86";
    constexpr char ICON_CH_ZG[]                      = "\xEE\x8D\x87";
    constexpr char ICON_CH_ZH[]                      = "\xEE\x8D\x88";
    constexpr char ICON_DE_BY[]                      = "\xEE\x8D\xA0";
    constexpr char ICON_DE_BY_ALT1[]                 = "\xEE\x8D\xA1";
    constexpr char ICON_ES_CT[]                      = "\xEE\x8D\xB0";
    constexpr char ICON_ES_PV[]                      = "\xEE\x8D\xB1";
    constexpr char ICON_FR_BRE[]                     = "\xEE\x8E\x80";
    constexpr char ICON_GB_AGY[]                     = "\xEE\x8E\x90";
    constexpr char ICON_GB_CON[]                     = "\xEE\x8E\x91";
    constexpr char ICON_GB_DEV[]                     = "\xEE\x8E\x92";
    constexpr char ICON_GB_DOR[]                     = "\xEE\x8E\x93";
    constexpr char ICON_GB_ENG[]                     = "\xEE\x8E\x94";
    constexpr char ICON_GB_FLN[]                     = "\xEE\x8E\x95";
    constexpr char ICON_GB_MON[]                     = "\xEE\x8E\x96";
    constexpr char ICON_GB_NBL[]                     = "\xEE\x8E\x97";
    constexpr char ICON_GB_NIR[]                     = "\xEE\x8E\x98";
    constexpr char ICON_GB_ORK[]                     = "\xEE\x8E\x99";
    constexpr char ICON_GB_PEM[]                     = "\xEE\x8E\x9A";
    constexpr char ICON_GB_SCT[]                     = "\xEE\x8E\x9B";
    constexpr char ICON_GB_SRY[]                     = "\xEE\x8E\x9C";
    constexpr char ICON_GB_VGL[]                     = "\xEE\x8E\x9D";
    constexpr char ICON_GB_WLS[]                     = "\xEE\x8E\x9E";
    constexpr char ICON_GB_XBR[]                     = "\xEE\x8E\x9F";
    constexpr char ICON_GB_XCA[]                     = "\xEE\x8E\xA0";
    constexpr char ICON_GB_XCR[]                     = "\xEE\x8E\xA1";
    constexpr char ICON_GB_XKD[]                     = "\xEE\x8E\xA2";
    constexpr char ICON_GB_XME[]                     = "\xEE\x8E\xA3";
    constexpr char ICON_GB_ZET[]                     = "\xEE\x8E\xA4";
    constexpr char ICON_IE_C[]                       = "\xEE\x8F\x80";
    constexpr char ICON_IE_L[]                       = "\xEE\x8F\x81";
    constexpr char ICON_IE_M[]                       = "\xEE\x8F\x82";
    constexpr char ICON_IE_U[]                       = "\xEE\x8F\x83";
    constexpr char ICON_IQ_KR[]                      = "\xEE\x8F\x90";
    constexpr char ICON_NL_FR[]                      = "\xEE\x8F\xA0";
    constexpr char ICON_US_AK[]                      = "\xEE\x90\x80";
    constexpr char ICON_US_AL[]                      = "\xEE\x90\x81";
    constexpr char ICON_US_AZ[]                      = "\xEE\x90\x82";
    constexpr char ICON_US_CA[]                      = "\xEE\x90\x83";
    constexpr char ICON_US_CO[]                      = "\xEE\x90\x84";
    constexpr char ICON_US_DC[]                      = "\xEE\x90\x85";
    constexpr char ICON_US_HI[]                      = "\xEE\x90\x86";
    constexpr char ICON_US_IN[]                      = "\xEE\x90\x87";
    constexpr char ICON_US_MD[]                      = "\xEE\x90\x88";
    constexpr char ICON_US_NM[]                      = "\xEE\x90\x89";
    constexpr char ICON_US_SC[]                      = "\xEE\x90\x8A";
    constexpr char ICON_US_TN[]                      = "\xEE\x90\x8B";
    constexpr char ICON_US_TX[]                      = "\xEE\x90\x8C";

    // ----- -----

    constexpr char ICON_ANDORRA[]                                  = "\xEE\x80\x83"; // U+E003 AD
    constexpr char ICON_UNITED_ARAB_EMIRATES[]                     = "\xEE\x80\x84"; // U+E004 AE
    constexpr char ICON_AFGHANISTAN[]                              = "\xEE\x80\x85"; // U+E005 AF
    constexpr char ICON_ANTIGUA_AND_BARBUDA[]                      = "\xEE\x80\x86"; // U+E006 AG
    constexpr char ICON_ANGUILLA[]                                 = "\xEE\x80\x88"; // U+E008 AI
    constexpr char ICON_ALBANIA[]                                  = "\xEE\x80\x8B"; // U+E00B AL
    constexpr char ICON_ARMENIA[]                                  = "\xEE\x80\x8C"; // U+E00C AM
    constexpr char ICON_ANGOLA[]                                   = "\xEE\x80\x8E"; // U+E00E AO
    constexpr char ICON_ANTARCTICA[]                               = "\xEE\x80\x90"; // U+E010 AQ
    constexpr char ICON_ARGENTINA[]                                = "\xEE\x80\x91"; // U+E011 AR
    constexpr char ICON_AMERICAN_SAMOA[]                           = "\xEE\x80\x92"; // U+E012 AS
    constexpr char ICON_AUSTRIA[]                                  = "\xEE\x80\x93"; // U+E013 AT
    constexpr char ICON_AUSTRALIA[]                                = "\xEE\x80\x94"; // U+E014 AU
    constexpr char ICON_ARUBA[]                                    = "\xEE\x80\x96"; // U+E016 AW
    constexpr char ICON_ÅLAND_ISLANDS[]                            = "\xEE\x80\x97"; // U+E017 AX
    constexpr char ICON_AZERBAIJAN[]                               = "\xEE\x80\x99"; // U+E019 AZ
    constexpr char ICON_BOSNIA_AND_HERZEGOVINA[]                   = "\xEE\x80\x9A"; // U+E01A BA
    constexpr char ICON_BARBADOS[]                                 = "\xEE\x80\x9B"; // U+E01B BB
    constexpr char ICON_BANGLADESH[]                               = "\xEE\x80\x9D"; // U+E01D BD
    constexpr char ICON_BELGIUM[]                                  = "\xEE\x80\x9E"; // U+E01E BE
    constexpr char ICON_BURKINA_FASO[]                             = "\xEE\x80\x9F"; // U+E01F BF
    constexpr char ICON_BULGARIA[]                                 = "\xEE\x80\xA0"; // U+E020 BG
    constexpr char ICON_BAHRAIN[]                                  = "\xEE\x80\xA1"; // U+E021 BH
    constexpr char ICON_BURUNDI[]                                  = "\xEE\x80\xA2"; // U+E022 BI
    constexpr char ICON_BENIN[]                                    = "\xEE\x80\xA3"; // U+E023 BJ
    constexpr char ICON_ST_BARTHÉLEMY[]                            = "\xEE\x80\xA5"; // U+E025 BL
    constexpr char ICON_BERMUDA[]                                  = "\xEE\x80\xA6"; // U+E026 BM
    constexpr char ICON_BRUNEI[]                                   = "\xEE\x80\xA7"; // U+E027 BN
    constexpr char ICON_BOLIVIA[]                                  = "\xEE\x80\xA8"; // U+E028 BO
    constexpr char ICON_CARIBBEAN_NETHERLANDS[]                    = "\xEE\x80\xAA"; // U+E02A BQ
    constexpr char ICON_BRAZIL[]                                   = "\xEE\x80\xAB"; // U+E02B BR
    constexpr char ICON_BAHAMAS[]                                  = "\xEE\x80\xAC"; // U+E02C BS
    constexpr char ICON_BHUTAN[]                                   = "\xEE\x80\xAD"; // U+E02D BT
    constexpr char ICON_BOUVET_ISLAND[]                            = "\xEE\x80\xAF"; // U+E02F BV
    constexpr char ICON_BOTSWANA[]                                 = "\xEE\x80\xB0"; // U+E030 BW
    constexpr char ICON_BELARUS[]                                  = "\xEE\x80\xB2"; // U+E032 BY
    constexpr char ICON_BELIZE[]                                   = "\xEE\x80\xB3"; // U+E033 BZ
    constexpr char ICON_CANADA[]                                   = "\xEE\x80\xB4"; // U+E034 CA
    constexpr char ICON_COCOS_KEELING_ISLANDS[]                    = "\xEE\x80\xB6"; // U+E036 CC
    constexpr char ICON_CONGO_KINSHASA[]                           = "\xEE\x80\xB7"; // U+E037 CD
    constexpr char ICON_CENTRAL_AFRICAN_REPUBLIC[]                 = "\xEE\x80\xB9"; // U+E039 CF
    constexpr char ICON_CONGO_BRAZZAVILLE[]                        = "\xEE\x80\xBA"; // U+E03A CG
    constexpr char ICON_SWITZERLAND[]                              = "\xEE\x80\xBB"; // U+E03B CH
    constexpr char ICON_CÔTE_DIVOIRE[]                             = "\xEE\x80\xBC"; // U+E03C CI
    constexpr char ICON_COOK_ISLANDS[]                             = "\xEE\x80\xBE"; // U+E03E CK
    constexpr char ICON_CHILE[]                                    = "\xEE\x80\xBF"; // U+E03F CL
    constexpr char ICON_CAMEROON[]                                 = "\xEE\x81\x80"; // U+E040 CM
    constexpr char ICON_CHINA[]                                    = "\xEE\x81\x81"; // U+E041 CN
    constexpr char ICON_COLOMBIA[]                                 = "\xEE\x81\x82"; // U+E042 CO
    constexpr char ICON_CLIPPERTON_ISLAND[]                        = "\xEE\x81\x83"; // U+E043 CP
    constexpr char ICON_SARK[]                                     = "\xEE\x81\x84"; // U+E044 CQ
    constexpr char ICON_COSTA_RICA[]                               = "\xEE\x81\x85"; // U+E045 CR
    constexpr char ICON_CUBA[]                                     = "\xEE\x81\x88"; // U+E048 CU
    constexpr char ICON_CAPE_VERDE[]                               = "\xEE\x81\x89"; // U+E049 CV
    constexpr char ICON_CURAÇAO[]                                  = "\xEE\x81\x8A"; // U+E04A CW
    constexpr char ICON_CHRISTMAS_ISLAND[]                         = "\xEE\x81\x8B"; // U+E04B CX
    constexpr char ICON_CYPRUS[]                                   = "\xEE\x81\x8C"; // U+E04C CY
    constexpr char ICON_CZECHIA[]                                  = "\xEE\x81\x8D"; // U+E04D CZ
    constexpr char ICON_GERMANY[]                                  = "\xEE\x81\x92"; // U+E052 DE
    constexpr char ICON_DJIBOUTI[]                                 = "\xEE\x81\x97"; // U+E057 DJ
    constexpr char ICON_DENMARK[]                                  = "\xEE\x81\x98"; // U+E058 DK
    constexpr char ICON_DOMINICA[]                                 = "\xEE\x81\x9A"; // U+E05A DM
    constexpr char ICON_DOMINICAN_REPUBLIC[]                       = "\xEE\x81\x9C"; // U+E05C DO
    constexpr char ICON_ALGERIA[]                                  = "\xEE\x81\xA7"; // U+E067 DZ
    constexpr char ICON_ECUADOR[]                                  = "\xEE\x81\xAA"; // U+E06A EC
    constexpr char ICON_ESTONIA[]                                  = "\xEE\x81\xAC"; // U+E06C EE
    constexpr char ICON_EGYPT[]                                    = "\xEE\x81\xAE"; // U+E06E EG
    constexpr char ICON_WESTERN_SAHARA[]                           = "\xEE\x81\xAF"; // U+E06F EH
    constexpr char ICON_ERITREA[]                                  = "\xEE\x81\xB9"; // U+E079 ER
    constexpr char ICON_SPAIN[]                                    = "\xEE\x81\xBA"; // U+E07A ES
    constexpr char ICON_ETHIOPIA[]                                 = "\xEE\x81\xBB"; // U+E07B ET
    constexpr char ICON_EUROPEAN_UNION[]                           = "\xEE\x81\xBC"; // U+E07C EU
    constexpr char ICON_FINLAND[]                                  = "\xEE\x82\x8A"; // U+E08A FI
    constexpr char ICON_FIJI[]                                     = "\xEE\x82\x8B"; // U+E08B FJ
    constexpr char ICON_FALKLAND_ISLANDS[]                         = "\xEE\x82\x8C"; // U+E08C FK
    constexpr char ICON_MICRONESIA[]                               = "\xEE\x82\x8E"; // U+E08E FM
    constexpr char ICON_FAROE_ISLANDS[]                            = "\xEE\x82\x90"; // U+E090 FO
    constexpr char ICON_FRANCE[]                                   = "\xEE\x82\x93"; // U+E093 FR
    constexpr char ICON_GABON[]                                    = "\xEE\x82\x9C"; // U+E09C GA
    constexpr char ICON_UNITED_KINGDOM[]                           = "\xEE\x82\x9D"; // U+E09D GB
    constexpr char ICON_GRENADA[]                                  = "\xEE\x82\x9F"; // U+E09F GD
    constexpr char ICON_GEORGIA[]                                  = "\xEE\x82\xA0"; // U+E0A0 GE
    constexpr char ICON_FRENCH_GUIANA[]                            = "\xEE\x82\xA1"; // U+E0A1 GF
    constexpr char ICON_GUERNSEY[]                                 = "\xEE\x82\xA2"; // U+E0A2 GG
    constexpr char ICON_GHANA[]                                    = "\xEE\x82\xA3"; // U+E0A3 GH
    constexpr char ICON_GIBRALTAR[]                                = "\xEE\x82\xA4"; // U+E0A4 GI
    constexpr char ICON_GREENLAND[]                                = "\xEE\x82\xA7"; // U+E0A7 GL
    constexpr char ICON_GAMBIA[]                                   = "\xEE\x82\xA8"; // U+E0A8 GM
    constexpr char ICON_GUINEA[]                                   = "\xEE\x82\xA9"; // U+E0A9 GN
    constexpr char ICON_GUADELOUPE[]                               = "\xEE\x82\xAB"; // U+E0AB GP
    constexpr char ICON_EQUATORIAL_GUINEA[]                        = "\xEE\x82\xAC"; // U+E0AC GQ
    constexpr char ICON_GREECE[]                                   = "\xEE\x82\xAD"; // U+E0AD GR
    constexpr char ICON_SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS[] = "\xEE\x82\xAE"; // U+E0AE GS
    constexpr char ICON_GUATEMALA[]                                = "\xEE\x82\xAF"; // U+E0AF GT
    constexpr char ICON_GUAM[]                                     = "\xEE\x82\xB0"; // U+E0B0 GU
    constexpr char ICON_GUINEA_BISSAU[]                            = "\xEE\x82\xB2"; // U+E0B2 GW
    constexpr char ICON_GUYANA[]                                   = "\xEE\x82\xB4"; // U+E0B4 GY
    constexpr char ICON_HONG_KONG_SAR_CHINA[]                      = "\xEE\x83\x80"; // U+E0C0 HK
    constexpr char ICON_HEARD_AND_MCDONALD_ISLANDS[]               = "\xEE\x83\x82"; // U+E0C2 HM
    constexpr char ICON_HONDURAS[]                                 = "\xEE\x83\x83"; // U+E0C3 HN
    constexpr char ICON_CROATIA[]                                  = "\xEE\x83\x87"; // U+E0C7 HR
    constexpr char ICON_HAITI[]                                    = "\xEE\x83\x89"; // U+E0C9 HT
    constexpr char ICON_HUNGARY[]                                  = "\xEE\x83\x8A"; // U+E0CA HU
    constexpr char ICON_INDONESIA[]                                = "\xEE\x83\x93"; // U+E0D3 ID
    constexpr char ICON_IRELAND[]                                  = "\xEE\x83\x94"; // U+E0D4 IE
    constexpr char ICON_ISRAEL[]                                   = "\xEE\x83\x9B"; // U+E0DB IL
    constexpr char ICON_ISLE_OF_MAN[]                              = "\xEE\x83\x9C"; // U+E0DC IM
    constexpr char ICON_INDIA[]                                    = "\xEE\x83\x9D"; // U+E0DD IN
    constexpr char ICON_BRITISH_INDIAN_OCEAN_TERRITORY[]           = "\xEE\x83\x9E"; // U+E0DE IO
    constexpr char ICON_IRAQ[]                                     = "\xEE\x83\xA0"; // U+E0E0 IQ
    constexpr char ICON_IRAN[]                                     = "\xEE\x83\xA1"; // U+E0E1 IR
    constexpr char ICON_ICELAND[]                                  = "\xEE\x83\xA2"; // U+E0E2 IS
    constexpr char ICON_ITALY[]                                    = "\xEE\x83\xA3"; // U+E0E3 IT
    constexpr char ICON_JERSEY[]                                   = "\xEE\x83\xAE"; // U+E0EE JE
    constexpr char ICON_JAMAICA[]                                  = "\xEE\x83\xB6"; // U+E0F6 JM
    constexpr char ICON_JORDAN[]                                   = "\xEE\x83\xB8"; // U+E0F8 JO
    constexpr char ICON_JAPAN[]                                    = "\xEE\x83\xB9"; // U+E0F9 JP
    constexpr char ICON_KENYA[]                                    = "\xEE\x84\x88"; // U+E108 KE
    constexpr char ICON_KYRGYZSTAN[]                               = "\xEE\x84\x8A"; // U+E10A KG
    constexpr char ICON_CAMBODIA[]                                 = "\xEE\x84\x8B"; // U+E10B KH
    constexpr char ICON_KIRIBATI[]                                 = "\xEE\x84\x8C"; // U+E10C KI
    constexpr char ICON_COMOROS[]                                  = "\xEE\x84\x90"; // U+E110 KM
    constexpr char ICON_ST_KITTS_AND_NEVIS[]                       = "\xEE\x84\x91"; // U+E111 KN
    constexpr char ICON_NORTH_KOREA[]                              = "\xEE\x84\x93"; // U+E113 KP
    constexpr char ICON_SOUTH_KOREA[]                              = "\xEE\x84\x95"; // U+E115 KR
    constexpr char ICON_KUWAIT[]                                   = "\xEE\x84\x9A"; // U+E11A KW
    constexpr char ICON_CAYMAN_ISLANDS[]                           = "\xEE\x84\x9C"; // U+E11C KY
    constexpr char ICON_KAZAKHSTAN[]                               = "\xEE\x84\x9D"; // U+E11D KZ
    constexpr char ICON_LAOS[]                                     = "\xEE\x84\x9E"; // U+E11E LA
    constexpr char ICON_LEBANON[]                                  = "\xEE\x84\x9F"; // U+E11F LB
    constexpr char ICON_ST_LUCIA[]                                 = "\xEE\x84\xA0"; // U+E120 LC
    constexpr char ICON_LIECHTENSTEIN[]                            = "\xEE\x84\xA6"; // U+E126 LI
    constexpr char ICON_SRI_LANKA[]                                = "\xEE\x84\xA8"; // U+E128 LK
    constexpr char ICON_LIBERIA[]                                  = "\xEE\x84\xAF"; // U+E12F LR
    constexpr char ICON_LESOTHO[]                                  = "\xEE\x84\xB0"; // U+E130 LS
    constexpr char ICON_LITHUANIA[]                                = "\xEE\x84\xB1"; // U+E131 LT
    constexpr char ICON_LUXEMBOURG[]                               = "\xEE\x84\xB2"; // U+E132 LU
    constexpr char ICON_LATVIA[]                                   = "\xEE\x84\xB3"; // U+E133 LV
    constexpr char ICON_LIBYA[]                                    = "\xEE\x84\xB6"; // U+E136 LY
    constexpr char ICON_MOROCCO[]                                  = "\xEE\x84\xB8"; // U+E138 MA
    constexpr char ICON_MONACO[]                                   = "\xEE\x84\xBA"; // U+E13A MC
    constexpr char ICON_MOLDOVA[]                                  = "\xEE\x84\xBB"; // U+E13B MD
    constexpr char ICON_MONTENEGRO[]                               = "\xEE\x84\xBC"; // U+E13C ME
    constexpr char ICON_ST_MARTIN[]                                = "\xEE\x84\xBD"; // U+E13D MF
    constexpr char ICON_MADAGASCAR[]                               = "\xEE\x84\xBE"; // U+E13E MG
    constexpr char ICON_MARSHALL_ISLANDS[]                         = "\xEE\x84\xBF"; // U+E13F MH
    constexpr char ICON_NORTH_MACEDONIA[]                          = "\xEE\x85\x82"; // U+E142 MK
    constexpr char ICON_MALI[]                                     = "\xEE\x85\x83"; // U+E143 ML
    constexpr char ICON_MYANMAR_BURMA[]                            = "\xEE\x85\x84"; // U+E144 MM
    constexpr char ICON_MONGOLIA[]                                 = "\xEE\x85\x85"; // U+E145 MN
    constexpr char ICON_MACAO_SAR_CHINA[]                          = "\xEE\x85\x86"; // U+E146 MO
    constexpr char ICON_NORTHERN_MARIANA_ISLANDS[]                 = "\xEE\x85\x87"; // U+E147 MP
    constexpr char ICON_MARTINIQUE[]                               = "\xEE\x85\x88"; // U+E148 MQ
    constexpr char ICON_MAURITANIA[]                               = "\xEE\x85\x89"; // U+E149 MR
    constexpr char ICON_MONTSERRAT[]                               = "\xEE\x85\x8A"; // U+E14A MS
    constexpr char ICON_MALTA[]                                    = "\xEE\x85\x8B"; // U+E14B MT
    constexpr char ICON_MAURITIUS[]                                = "\xEE\x85\x8C"; // U+E14C MU
    constexpr char ICON_MALDIVES[]                                 = "\xEE\x85\x8D"; // U+E14D MV
    constexpr char ICON_MALAWI[]                                   = "\xEE\x85\x8E"; // U+E14E MW
    constexpr char ICON_MEXICO[]                                   = "\xEE\x85\x8F"; // U+E14F MX
    constexpr char ICON_MALAYSIA[]                                 = "\xEE\x85\x90"; // U+E150 MY
    constexpr char ICON_MOZAMBIQUE[]                               = "\xEE\x85\x91"; // U+E151 MZ
    constexpr char ICON_NAMIBIA[]                                  = "\xEE\x85\x92"; // U+E152 NA
    constexpr char ICON_NEW_CALEDONIA[]                            = "\xEE\x85\x94"; // U+E154 NC
    constexpr char ICON_NIGER[]                                    = "\xEE\x85\x96"; // U+E156 NE
    constexpr char ICON_NORFOLK_ISLAND[]                           = "\xEE\x85\x97"; // U+E157 NF
    constexpr char ICON_NIGERIA[]                                  = "\xEE\x85\x98"; // U+E158 NG
    constexpr char ICON_NICARAGUA[]                                = "\xEE\x85\x9A"; // U+E15A NI
    constexpr char ICON_NETHERLANDS[]                              = "\xEE\x85\x9D"; // U+E15D NL
    constexpr char ICON_NORWAY[]                                   = "\xEE\x85\xA0"; // U+E160 NO
    constexpr char ICON_NEPAL[]                                    = "\xEE\x85\xA1"; // U+E161 NP
    constexpr char ICON_NAURU[]                                    = "\xEE\x85\xA3"; // U+E163 NR
    constexpr char ICON_NIUE[]                                     = "\xEE\x85\xA6"; // U+E166 NU
    constexpr char ICON_NEW_ZEALAND[]                              = "\xEE\x85\xAB"; // U+E16B NZ
    constexpr char ICON_OMAN[]                                     = "\xEE\x85\xB8"; // U+E178 OM
    constexpr char ICON_PANAMA[]                                   = "\xEE\x86\x86"; // U+E186 PA
    constexpr char ICON_PERU[]                                     = "\xEE\x86\x8A"; // U+E18A PE
    constexpr char ICON_FRENCH_POLYNESIA[]                         = "\xEE\x86\x8B"; // U+E18B PF
    constexpr char ICON_PAPUA_NEW_GUINEA[]                         = "\xEE\x86\x8C"; // U+E18C PG
    constexpr char ICON_PHILIPPINES[]                              = "\xEE\x86\x8D"; // U+E18D PH
    constexpr char ICON_PAKISTAN[]                                 = "\xEE\x86\x90"; // U+E190 PK
    constexpr char ICON_POLAND[]                                   = "\xEE\x86\x91"; // U+E191 PL
    constexpr char ICON_ST_PIERRE_AND_MIQUELON[]                   = "\xEE\x86\x92"; // U+E192 PM
    constexpr char ICON_PITCAIRN_ISLANDS[]                         = "\xEE\x86\x93"; // U+E193 PN
    constexpr char ICON_PUERTO_RICO[]                              = "\xEE\x86\x97"; // U+E197 PR
    constexpr char ICON_PALESTINIAN_TERRITORIES[]                  = "\xEE\x86\x98"; // U+E198 PS
    constexpr char ICON_PORTUGAL[]                                 = "\xEE\x86\x99"; // U+E199 PT
    constexpr char ICON_PALAU[]                                    = "\xEE\x86\x9C"; // U+E19C PW
    constexpr char ICON_PARAGUAY[]                                 = "\xEE\x86\x9E"; // U+E19E PY
    constexpr char ICON_QATAR[]                                    = "\xEE\x86\xA0"; // U+E1A0 QA
    constexpr char ICON_RÉUNION[]                                  = "\xEE\x86\xBE"; // U+E1BE RE
    constexpr char ICON_ROMANIA[]                                  = "\xEE\x87\x88"; // U+E1C8 RO
    constexpr char ICON_SERBIA[]                                   = "\xEE\x87\x8C"; // U+E1CC RS
    constexpr char ICON_RUSSIA[]                                   = "\xEE\x87\x8E"; // U+E1CE RU
    constexpr char ICON_RWANDA[]                                   = "\xEE\x87\x90"; // U+E1D0 RW
    constexpr char ICON_SAUDI_ARABIA[]                             = "\xEE\x87\x94"; // U+E1D4 SA
    constexpr char ICON_SOLOMON_ISLANDS[]                          = "\xEE\x87\x95"; // U+E1D5 SB
    constexpr char ICON_SEYCHELLES[]                               = "\xEE\x87\x96"; // U+E1D6 SC
    constexpr char ICON_SUDAN[]                                    = "\xEE\x87\x97"; // U+E1D7 SD
    constexpr char ICON_SWEDEN[]                                   = "\xEE\x87\x98"; // U+E1D8 SE
    constexpr char ICON_SINGAPORE[]                                = "\xEE\x87\x9A"; // U+E1DA SG
    constexpr char ICON_ST_HELENA[]                                = "\xEE\x87\x9B"; // U+E1DB SH
    constexpr char ICON_SLOVENIA[]                                 = "\xEE\x87\x9C"; // U+E1DC SI
    constexpr char ICON_SVALBARD_AND_JAN_MAYEN[]                   = "\xEE\x87\x9D"; // U+E1DD SJ
    constexpr char ICON_SLOVAKIA[]                                 = "\xEE\x87\x9E"; // U+E1DE SK
    constexpr char ICON_SIERRA_LEONE[]                             = "\xEE\x87\x9F"; // U+E1DF SL
    constexpr char ICON_SAN_MARINO[]                               = "\xEE\x87\xA0"; // U+E1E0 SM
    constexpr char ICON_SENEGAL[]                                  = "\xEE\x87\xA1"; // U+E1E1 SN
    constexpr char ICON_SOMALIA[]                                  = "\xEE\x87\xA2"; // U+E1E2 SO
    constexpr char ICON_SURINAME[]                                 = "\xEE\x87\xA5"; // U+E1E5 SR
    constexpr char ICON_SOUTH_SUDAN[]                              = "\xEE\x87\xA6"; // U+E1E6 SS
    constexpr char ICON_SÃO_TOMÉ_AND_PRÍNCIPE[]                    = "\xEE\x87\xA7"; // U+E1E7 ST
    constexpr char ICON_EL_SALVADOR[]                              = "\xEE\x87\xA9"; // U+E1E9 SV
    constexpr char ICON_SINT_MAARTEN[]                             = "\xEE\x87\xAB"; // U+E1EB SX
    constexpr char ICON_SYRIA[]                                    = "\xEE\x87\xAC"; // U+E1EC SY
    constexpr char ICON_ESWATINI[]                                 = "\xEE\x87\xAD"; // U+E1ED SZ
    constexpr char ICON_TURKS_AND_CAICOS_ISLANDS[]                 = "\xEE\x87\xB0"; // U+E1F0 TC
    constexpr char ICON_CHAD[]                                     = "\xEE\x87\xB1"; // U+E1F1 TD
    constexpr char ICON_FRENCH_SOUTHERN_TERRITORIES[]              = "\xEE\x87\xB3"; // U+E1F3 TF
    constexpr char ICON_TOGO[]                                     = "\xEE\x87\xB4"; // U+E1F4 TG
    constexpr char ICON_THAILAND[]                                 = "\xEE\x87\xB5"; // U+E1F5 TH
    constexpr char ICON_TAJIKISTAN[]                               = "\xEE\x87\xB7"; // U+E1F7 TJ
    constexpr char ICON_TOKELAU[]                                  = "\xEE\x87\xB8"; // U+E1F8 TK
    constexpr char ICON_TIMOR_LESTE[]                              = "\xEE\x87\xB9"; // U+E1F9 TL
    constexpr char ICON_TURKMENISTAN[]                             = "\xEE\x87\xBA"; // U+E1FA TM
    constexpr char ICON_TUNISIA[]                                  = "\xEE\x87\xBB"; // U+E1FB TN
    constexpr char ICON_TONGA[]                                    = "\xEE\x87\xBC"; // U+E1FC TO
    constexpr char ICON_TÜRKIYE[]                                  = "\xEE\x87\xBF"; // U+E1FF TR
    constexpr char ICON_TRINIDAD_AND_TOBAGO[]                      = "\xEE\x88\x81"; // U+E201 TT
    constexpr char ICON_TUVALU[]                                   = "\xEE\x88\x83"; // U+E203 TV
    constexpr char ICON_TAIWAN[]                                   = "\xEE\x88\x84"; // U+E204 TW
    constexpr char ICON_TANZANIA[]                                 = "\xEE\x88\x87"; // U+E207 TZ
    constexpr char ICON_UKRAINE[]                                  = "\xEE\x88\x88"; // U+E208 UA
    constexpr char ICON_UGANDA[]                                   = "\xEE\x88\x8E"; // U+E20E UG
    constexpr char ICON_US_OUTLYING_ISLANDS[]                      = "\xEE\x88\x94"; // U+E214 UM
    constexpr char ICON_UNITED_NATIONS[]                           = "\xEE\x88\x95"; // U+E215 UN
    constexpr char ICON_UNITED_STATES[]                            = "\xEE\x88\x9A"; // U+E21A US
    constexpr char ICON_URUGUAY[]                                  = "\xEE\x88\xA0"; // U+E220 UY
    constexpr char ICON_UZBEKISTAN[]                               = "\xEE\x88\xA1"; // U+E221 UZ
    constexpr char ICON_VATICAN_CITY[]                             = "\xEE\x88\xA2"; // U+E222 VA
    constexpr char ICON_ST_VINCENT_AND_GRENADINES[]                = "\xEE\x88\xA4"; // U+E224 VC
    constexpr char ICON_VENEZUELA[]                                = "\xEE\x88\xA6"; // U+E226 VE
    constexpr char ICON_BRITISH_VIRGIN_ISLANDS[]                   = "\xEE\x88\xA8"; // U+E228 VG
    constexpr char ICON_US_VIRGIN_ISLANDS[]                        = "\xEE\x88\xAA"; // U+E22A VI
    constexpr char ICON_VIETNAM[]                                  = "\xEE\x88\xAF"; // U+E22F VN
    constexpr char ICON_VANUATU[]                                  = "\xEE\x88\xB6"; // U+E236 VU
    constexpr char ICON_WALLIS_AND_FUTUNA[]                        = "\xEE\x89\x81"; // U+E241 WF
    constexpr char ICON_SAMOA[]                                    = "\xEE\x89\x8E"; // U+E24E WS
    constexpr char ICON_KOSOVO[]                                   = "\xEE\x89\xA0"; // U+E260 XK
    constexpr char ICON_YEMEN[]                                    = "\xEE\x89\xB4"; // U+E274 YE
    constexpr char ICON_MAYOTTE[]                                  = "\xEE\x8A\x83"; // U+E283 YT
    constexpr char ICON_SOUTH_AFRICA[]                             = "\xEE\x8A\x8A"; // U+E28A ZA
    constexpr char ICON_ZAMBIA[]                                   = "\xEE\x8A\x96"; // U+E296 ZM
    constexpr char ICON_ZIMBABWE[]                                 = "\xEE\x8A\xA0"; // U+E2A0 ZW
}
