#pragma once

namespace Fonts
{
    const constexpr char ICON_AD[]     = "\xEE\x80\x83"; // U+E003 Andorra
    const constexpr char ICON_AE[]     = "\xEE\x80\x84"; // U+E004 United Arab Emirates
    const constexpr char ICON_AF[]     = "\xEE\x80\x85"; // U+E005 Afghanistan
    const constexpr char ICON_AG[]     = "\xEE\x80\x86"; // U+E006 Antigua & Barbuda
    const constexpr char ICON_AI[]     = "\xEE\x80\x88"; // U+E008 Anguilla
    const constexpr char ICON_AL[]     = "\xEE\x80\x8B"; // U+E00B Albania
    const constexpr char ICON_AM[]     = "\xEE\x80\x8C"; // U+E00C Armenia
    const constexpr char ICON_AO[]     = "\xEE\x80\x8E"; // U+E00E Angola
    const constexpr char ICON_AQ[]     = "\xEE\x80\x90"; // U+E010 Antarctica
    const constexpr char ICON_AR[]     = "\xEE\x80\x91"; // U+E011 Argentina
    const constexpr char ICON_AS[]     = "\xEE\x80\x92"; // U+E012 American Samoa
    const constexpr char ICON_AT[]     = "\xEE\x80\x93"; // U+E013 Austria
    const constexpr char ICON_AU[]     = "\xEE\x80\x94"; // U+E014 Australia
    const constexpr char ICON_AW[]     = "\xEE\x80\x96"; // U+E016 Aruba
    const constexpr char ICON_AX[]     = "\xEE\x80\x97"; // U+E017 Åland Islands
    const constexpr char ICON_AZ[]     = "\xEE\x80\x99"; // U+E019 Azerbaijan
    const constexpr char ICON_BA[]     = "\xEE\x80\x9A"; // U+E01A Bosnia & Herzegovina
    const constexpr char ICON_BB[]     = "\xEE\x80\x9B"; // U+E01B Barbados
    const constexpr char ICON_BD[]     = "\xEE\x80\x9D"; // U+E01D Bangladesh
    const constexpr char ICON_BE[]     = "\xEE\x80\x9E"; // U+E01E Belgium
    const constexpr char ICON_BF[]     = "\xEE\x80\x9F"; // U+E01F Burkina Faso
    const constexpr char ICON_BG[]     = "\xEE\x80\xA0"; // U+E020 Bulgaria
    const constexpr char ICON_BH[]     = "\xEE\x80\xA1"; // U+E021 Bahrain
    const constexpr char ICON_BI[]     = "\xEE\x80\xA2"; // U+E022 Burundi
    const constexpr char ICON_BJ[]     = "\xEE\x80\xA3"; // U+E023 Benin
    const constexpr char ICON_BL[]     = "\xEE\x80\xA5"; // U+E025 St. Barthélemy
    const constexpr char ICON_BM[]     = "\xEE\x80\xA6"; // U+E026 Bermuda
    const constexpr char ICON_BN[]     = "\xEE\x80\xA7"; // U+E027 Brunei
    const constexpr char ICON_BO[]     = "\xEE\x80\xA8"; // U+E028 Bolivia
    const constexpr char ICON_BQ[]     = "\xEE\x80\xAA"; // U+E02A Caribbean Netherlands
    const constexpr char ICON_BR[]     = "\xEE\x80\xAB"; // U+E02B Brazil
    const constexpr char ICON_BS[]     = "\xEE\x80\xAC"; // U+E02C Bahamas
    const constexpr char ICON_BT[]     = "\xEE\x80\xAD"; // U+E02D Bhutan
    const constexpr char ICON_BV[]     = "\xEE\x80\xAF"; // U+E02F Bouvet Island
    const constexpr char ICON_BW[]     = "\xEE\x80\xB0"; // U+E030 Botswana
    const constexpr char ICON_BY[]     = "\xEE\x80\xB2"; // U+E032 Belarus
    const constexpr char ICON_BZ[]     = "\xEE\x80\xB3"; // U+E033 Belize
    const constexpr char ICON_CA[]     = "\xEE\x80\xB4"; // U+E034 Canada
    const constexpr char ICON_CC[]     = "\xEE\x80\xB6"; // U+E036 Cocos (Keeling) Islands
    const constexpr char ICON_CD[]     = "\xEE\x80\xB7"; // U+E037 Congo - Kinshasa
    const constexpr char ICON_CF[]     = "\xEE\x80\xB9"; // U+E039 Central African Republic
    const constexpr char ICON_CG[]     = "\xEE\x80\xBA"; // U+E03A Congo - Brazzaville
    const constexpr char ICON_CH[]     = "\xEE\x80\xBB"; // U+E03B Switzerland
    const constexpr char ICON_CI[]     = "\xEE\x80\xBC"; // U+E03C Côte d’Ivoire
    const constexpr char ICON_CK[]     = "\xEE\x80\xBE"; // U+E03E Cook Islands
    const constexpr char ICON_CL[]     = "\xEE\x80\xBF"; // U+E03F Chile
    const constexpr char ICON_CM[]     = "\xEE\x81\x80"; // U+E040 Cameroon
    const constexpr char ICON_CN[]     = "\xEE\x81\x81"; // U+E041 China
    const constexpr char ICON_CO[]     = "\xEE\x81\x82"; // U+E042 Colombia
    const constexpr char ICON_CP[]     = "\xEE\x81\x83"; // U+E043 Clipperton Island
    const constexpr char ICON_CQ[]     = "\xEE\x81\x84"; // U+E044 Sark
    const constexpr char ICON_CR[]     = "\xEE\x81\x85"; // U+E045 Costa Rica
    const constexpr char ICON_CS[]     = "\xEE\x81\x86";
    const constexpr char ICON_CU[]     = "\xEE\x81\x88"; // U+E048 Cuba
    const constexpr char ICON_CV[]     = "\xEE\x81\x89"; // U+E049 Cape Verde
    const constexpr char ICON_CW[]     = "\xEE\x81\x8A"; // U+E04A Curaçao
    const constexpr char ICON_CX[]     = "\xEE\x81\x8B"; // U+E04B Christmas Island
    const constexpr char ICON_CY[]     = "\xEE\x81\x8C"; // U+E04C Cyprus
    const constexpr char ICON_CZ[]     = "\xEE\x81\x8D"; // U+E04D Czechia
    const constexpr char ICON_DD[]     = "\xEE\x81\x91";
    const constexpr char ICON_DE[]     = "\xEE\x81\x92"; // U+E052 Germany
    const constexpr char ICON_DJ[]     = "\xEE\x81\x97"; // U+E057 Djibouti
    const constexpr char ICON_DK[]     = "\xEE\x81\x98"; // U+E058 Denmark
    const constexpr char ICON_DM[]     = "\xEE\x81\x9A"; // U+E05A Dominica
    const constexpr char ICON_DO[]     = "\xEE\x81\x9C"; // U+E05C Dominican Republic
    const constexpr char ICON_DZ[]     = "\xEE\x81\xA7"; // U+E067 Algeria
    const constexpr char ICON_EC[]     = "\xEE\x81\xAA"; // U+E06A Ecuador
    const constexpr char ICON_EE[]     = "\xEE\x81\xAC"; // U+E06C Estonia
    const constexpr char ICON_EG[]     = "\xEE\x81\xAE"; // U+E06E Egypt
    const constexpr char ICON_EH[]     = "\xEE\x81\xAF"; // U+E06F Western Sahara
    const constexpr char ICON_ER[]     = "\xEE\x81\xB9"; // U+E079 Eritrea
    const constexpr char ICON_ES[]     = "\xEE\x81\xBA"; // U+E07A Spain
    const constexpr char ICON_ET[]     = "\xEE\x81\xBB"; // U+E07B Ethiopia
    const constexpr char ICON_EU[]     = "\xEE\x81\xBC"; // U+E07C European Union
    const constexpr char ICON_FI[]     = "\xEE\x82\x8A"; // U+E08A Finland
    const constexpr char ICON_FJ[]     = "\xEE\x82\x8B"; // U+E08B Fiji
    const constexpr char ICON_FK[]     = "\xEE\x82\x8C"; // U+E08C Falkland Islands
    const constexpr char ICON_FM[]     = "\xEE\x82\x8E"; // U+E08E Micronesia
    const constexpr char ICON_FO[]     = "\xEE\x82\x90"; // U+E090 Faroe Islands
    const constexpr char ICON_FR[]     = "\xEE\x82\x93"; // U+E093 France
    const constexpr char ICON_GA[]     = "\xEE\x82\x9C"; // U+E09C Gabon
    const constexpr char ICON_GB[]     = "\xEE\x82\x9D"; // U+E09D United Kingdom
    const constexpr char ICON_GD[]     = "\xEE\x82\x9F"; // U+E09F Grenada
    const constexpr char ICON_GE[]     = "\xEE\x82\xA0"; // U+E0A0 Georgia
    const constexpr char ICON_GF[]     = "\xEE\x82\xA1"; // U+E0A1 French Guiana
    const constexpr char ICON_GG[]     = "\xEE\x82\xA2"; // U+E0A2 Guernsey
    const constexpr char ICON_GH[]     = "\xEE\x82\xA3"; // U+E0A3 Ghana
    const constexpr char ICON_GI[]     = "\xEE\x82\xA4"; // U+E0A4 Gibraltar
    const constexpr char ICON_GL[]     = "\xEE\x82\xA7"; // U+E0A7 Greenland
    const constexpr char ICON_GM[]     = "\xEE\x82\xA8"; // U+E0A8 Gambia
    const constexpr char ICON_GN[]     = "\xEE\x82\xA9"; // U+E0A9 Guinea
    const constexpr char ICON_GP[]     = "\xEE\x82\xAB"; // U+E0AB Guadeloupe
    const constexpr char ICON_GQ[]     = "\xEE\x82\xAC"; // U+E0AC Equatorial Guinea
    const constexpr char ICON_GR[]     = "\xEE\x82\xAD"; // U+E0AD Greece
    const constexpr char ICON_GS[]     = "\xEE\x82\xAE"; // U+E0AE South Georgia & South Sandwich Islands
    const constexpr char ICON_GT[]     = "\xEE\x82\xAF"; // U+E0AF Guatemala
    const constexpr char ICON_GU[]     = "\xEE\x82\xB0"; // U+E0B0 Guam
    const constexpr char ICON_GW[]     = "\xEE\x82\xB2"; // U+E0B2 Guinea-Bissau
    const constexpr char ICON_GY[]     = "\xEE\x82\xB4"; // U+E0B4 Guyana
    const constexpr char ICON_HK[]     = "\xEE\x83\x80"; // U+E0C0 Hong Kong SAR China
    const constexpr char ICON_HM[]     = "\xEE\x83\x82"; // U+E0C2 Heard & McDonald Islands
    const constexpr char ICON_HN[]     = "\xEE\x83\x83"; // U+E0C3 Honduras
    const constexpr char ICON_HR[]     = "\xEE\x83\x87"; // U+E0C7 Croatia
    const constexpr char ICON_HT[]     = "\xEE\x83\x89"; // U+E0C9 Haiti
    const constexpr char ICON_HU[]     = "\xEE\x83\x8A"; // U+E0CA Hungary
    const constexpr char ICON_ID[]     = "\xEE\x83\x93"; // U+E0D3 Indonesia
    const constexpr char ICON_IE[]     = "\xEE\x83\x94"; // U+E0D4 Ireland
    const constexpr char ICON_IL[]     = "\xEE\x83\x9B"; // U+E0DB Israel
    const constexpr char ICON_IM[]     = "\xEE\x83\x9C"; // U+E0DC Isle of Man
    const constexpr char ICON_IN[]     = "\xEE\x83\x9D"; // U+E0DD India
    const constexpr char ICON_IO[]     = "\xEE\x83\x9E"; // U+E0DE British Indian Ocean Territory
    const constexpr char ICON_IQ[]     = "\xEE\x83\xA0"; // U+E0E0 Iraq
    const constexpr char ICON_IR[]     = "\xEE\x83\xA1"; // U+E0E1 Iran
    const constexpr char ICON_IS[]     = "\xEE\x83\xA2"; // U+E0E2 Iceland
    const constexpr char ICON_IT[]     = "\xEE\x83\xA3"; // U+E0E3 Italy
    const constexpr char ICON_JE[]     = "\xEE\x83\xAE"; // U+E0EE Jersey
    const constexpr char ICON_JM[]     = "\xEE\x83\xB6"; // U+E0F6 Jamaica
    const constexpr char ICON_JO[]     = "\xEE\x83\xB8"; // U+E0F8 Jordan
    const constexpr char ICON_JP[]     = "\xEE\x83\xB9"; // U+E0F9 Japan
    const constexpr char ICON_KE[]     = "\xEE\x84\x88"; // U+E108 Kenya
    const constexpr char ICON_KG[]     = "\xEE\x84\x8A"; // U+E10A Kyrgyzstan
    const constexpr char ICON_KH[]     = "\xEE\x84\x8B"; // U+E10B Cambodia
    const constexpr char ICON_KI[]     = "\xEE\x84\x8C"; // U+E10C Kiribati
    const constexpr char ICON_KM[]     = "\xEE\x84\x90"; // U+E110 Comoros
    const constexpr char ICON_KN[]     = "\xEE\x84\x91"; // U+E111 St. Kitts & Nevis
    const constexpr char ICON_KP[]     = "\xEE\x84\x93"; // U+E113 North Korea
    const constexpr char ICON_KR[]     = "\xEE\x84\x95"; // U+E115 South Korea
    const constexpr char ICON_KW[]     = "\xEE\x84\x9A"; // U+E11A Kuwait
    const constexpr char ICON_KY[]     = "\xEE\x84\x9C"; // U+E11C Cayman Islands
    const constexpr char ICON_KZ[]     = "\xEE\x84\x9D"; // U+E11D Kazakhstan
    const constexpr char ICON_LA[]     = "\xEE\x84\x9E"; // U+E11E Laos
    const constexpr char ICON_LB[]     = "\xEE\x84\x9F"; // U+E11F Lebanon
    const constexpr char ICON_LC[]     = "\xEE\x84\xA0"; // U+E120 St. Lucia
    const constexpr char ICON_LI[]     = "\xEE\x84\xA6"; // U+E126 Liechtenstein
    const constexpr char ICON_LK[]     = "\xEE\x84\xA8"; // U+E128 Sri Lanka
    const constexpr char ICON_LR[]     = "\xEE\x84\xAF"; // U+E12F Liberia
    const constexpr char ICON_LS[]     = "\xEE\x84\xB0"; // U+E130 Lesotho
    const constexpr char ICON_LT[]     = "\xEE\x84\xB1"; // U+E131 Lithuania
    const constexpr char ICON_LU[]     = "\xEE\x84\xB2"; // U+E132 Luxembourg
    const constexpr char ICON_LV[]     = "\xEE\x84\xB3"; // U+E133 Latvia
    const constexpr char ICON_LY[]     = "\xEE\x84\xB6"; // U+E136 Libya
    const constexpr char ICON_MA[]     = "\xEE\x84\xB8"; // U+E138 Morocco
    const constexpr char ICON_MC[]     = "\xEE\x84\xBA"; // U+E13A Monaco
    const constexpr char ICON_MD[]     = "\xEE\x84\xBB"; // U+E13B Moldova
    const constexpr char ICON_ME[]     = "\xEE\x84\xBC"; // U+E13C Montenegro
    const constexpr char ICON_MF[]     = "\xEE\x84\xBD"; // U+E13D St. Martin
    const constexpr char ICON_MG[]     = "\xEE\x84\xBE"; // U+E13E Madagascar
    const constexpr char ICON_MH[]     = "\xEE\x84\xBF"; // U+E13F Marshall Islands
    const constexpr char ICON_MK[]     = "\xEE\x85\x82"; // U+E142 North Macedonia
    const constexpr char ICON_ML[]     = "\xEE\x85\x83"; // U+E143 Mali
    const constexpr char ICON_MM[]     = "\xEE\x85\x84"; // U+E144 Myanmar (Burma)
    const constexpr char ICON_MN[]     = "\xEE\x85\x85"; // U+E145 Mongolia
    const constexpr char ICON_MO[]     = "\xEE\x85\x86"; // U+E146 Macao SAR China
    const constexpr char ICON_MP[]     = "\xEE\x85\x87"; // U+E147 Northern Mariana Islands
    const constexpr char ICON_MQ[]     = "\xEE\x85\x88"; // U+E148 Martinique
    const constexpr char ICON_MR[]     = "\xEE\x85\x89"; // U+E149 Mauritania
    const constexpr char ICON_MS[]     = "\xEE\x85\x8A"; // U+E14A Montserrat
    const constexpr char ICON_MT[]     = "\xEE\x85\x8B"; // U+E14B Malta
    const constexpr char ICON_MU[]     = "\xEE\x85\x8C"; // U+E14C Mauritius
    const constexpr char ICON_MV[]     = "\xEE\x85\x8D"; // U+E14D Maldives
    const constexpr char ICON_MW[]     = "\xEE\x85\x8E"; // U+E14E Malawi
    const constexpr char ICON_MX[]     = "\xEE\x85\x8F"; // U+E14F Mexico
    const constexpr char ICON_MY[]     = "\xEE\x85\x90"; // U+E150 Malaysia
    const constexpr char ICON_MZ[]     = "\xEE\x85\x91"; // U+E151 Mozambique
    const constexpr char ICON_NA[]     = "\xEE\x85\x92"; // U+E152 Namibia
    const constexpr char ICON_NC[]     = "\xEE\x85\x94"; // U+E154 New Caledonia
    const constexpr char ICON_NE[]     = "\xEE\x85\x96"; // U+E156 Niger
    const constexpr char ICON_NF[]     = "\xEE\x85\x97"; // U+E157 Norfolk Island
    const constexpr char ICON_NG[]     = "\xEE\x85\x98"; // U+E158 Nigeria
    const constexpr char ICON_NI[]     = "\xEE\x85\x9A"; // U+E15A Nicaragua
    const constexpr char ICON_NL[]     = "\xEE\x85\x9D"; // U+E15D Netherlands
    const constexpr char ICON_NO[]     = "\xEE\x85\xA0"; // U+E160 Norway
    const constexpr char ICON_NP[]     = "\xEE\x85\xA1"; // U+E161 Nepal
    const constexpr char ICON_NR[]     = "\xEE\x85\xA3"; // U+E163 Nauru
    const constexpr char ICON_NU[]     = "\xEE\x85\xA6"; // U+E166 Niue
    const constexpr char ICON_NZ[]     = "\xEE\x85\xAB"; // U+E16B New Zealand
    const constexpr char ICON_OM[]     = "\xEE\x85\xB8"; // U+E178 Oman
    const constexpr char ICON_PA[]     = "\xEE\x86\x86"; // U+E186 Panama
    const constexpr char ICON_PE[]     = "\xEE\x86\x8A"; // U+E18A Peru
    const constexpr char ICON_PF[]     = "\xEE\x86\x8B"; // U+E18B French Polynesia
    const constexpr char ICON_PG[]     = "\xEE\x86\x8C"; // U+E18C Papua New Guinea
    const constexpr char ICON_PH[]     = "\xEE\x86\x8D"; // U+E18D Philippines
    const constexpr char ICON_PK[]     = "\xEE\x86\x90"; // U+E190 Pakistan
    const constexpr char ICON_PL[]     = "\xEE\x86\x91"; // U+E191 Poland
    const constexpr char ICON_PM[]     = "\xEE\x86\x92"; // U+E192 St. Pierre & Miquelon
    const constexpr char ICON_PN[]     = "\xEE\x86\x93"; // U+E193 Pitcairn Islands
    const constexpr char ICON_PR[]     = "\xEE\x86\x97"; // U+E197 Puerto Rico
    const constexpr char ICON_PS[]     = "\xEE\x86\x98"; // U+E198 Palestinian Territories
    const constexpr char ICON_PT[]     = "\xEE\x86\x99"; // U+E199 Portugal
    const constexpr char ICON_PW[]     = "\xEE\x86\x9C"; // U+E19C Palau
    const constexpr char ICON_PY[]     = "\xEE\x86\x9E"; // U+E19E Paraguay
    const constexpr char ICON_QA[]     = "\xEE\x86\xA0"; // U+E1A0 Qatar
    const constexpr char ICON_RE[]     = "\xEE\x86\xBE"; // U+E1BE Réunion
    const constexpr char ICON_RO[]     = "\xEE\x87\x88"; // U+E1C8 Romania
    const constexpr char ICON_RS[]     = "\xEE\x87\x8C"; // U+E1CC Serbia
    const constexpr char ICON_RU[]     = "\xEE\x87\x8E"; // U+E1CE Russia
    const constexpr char ICON_RW[]     = "\xEE\x87\x90"; // U+E1D0 Rwanda
    const constexpr char ICON_SA[]     = "\xEE\x87\x94"; // U+E1D4 Saudi Arabia
    const constexpr char ICON_SB[]     = "\xEE\x87\x95"; // U+E1D5 Solomon Islands
    const constexpr char ICON_SC[]     = "\xEE\x87\x96"; // U+E1D6 Seychelles
    const constexpr char ICON_SD[]     = "\xEE\x87\x97"; // U+E1D7 Sudan
    const constexpr char ICON_SE[]     = "\xEE\x87\x98"; // U+E1D8 Sweden
    const constexpr char ICON_SG[]     = "\xEE\x87\x9A"; // U+E1DA Singapore
    const constexpr char ICON_SH[]     = "\xEE\x87\x9B"; // U+E1DB St. Helena
    const constexpr char ICON_SI[]     = "\xEE\x87\x9C"; // U+E1DC Slovenia
    const constexpr char ICON_SJ[]     = "\xEE\x87\x9D"; // U+E1DD Svalbard & Jan Mayen
    const constexpr char ICON_SK[]     = "\xEE\x87\x9E"; // U+E1DE Slovakia
    const constexpr char ICON_SL[]     = "\xEE\x87\x9F"; // U+E1DF Sierra Leone
    const constexpr char ICON_SM[]     = "\xEE\x87\xA0"; // U+E1E0 San Marino
    const constexpr char ICON_SN[]     = "\xEE\x87\xA1"; // U+E1E1 Senegal
    const constexpr char ICON_SO[]     = "\xEE\x87\xA2"; // U+E1E2 Somalia
    const constexpr char ICON_SR[]     = "\xEE\x87\xA5"; // U+E1E5 Suriname
    const constexpr char ICON_SS[]     = "\xEE\x87\xA6"; // U+E1E6 South Sudan
    const constexpr char ICON_ST[]     = "\xEE\x87\xA7"; // U+E1E7 São Tomé & Príncipe
    const constexpr char ICON_SU[]     = "\xEE\x87\xA8";
    const constexpr char ICON_SV[]     = "\xEE\x87\xA9"; // U+E1E9 El Salvador
    const constexpr char ICON_SX[]     = "\xEE\x87\xAB"; // U+E1EB Sint Maarten
    const constexpr char ICON_SY[]     = "\xEE\x87\xAC"; // U+E1EC Syria
    const constexpr char ICON_SZ[]     = "\xEE\x87\xAD"; // U+E1ED Eswatini
    const constexpr char ICON_TC[]     = "\xEE\x87\xB0"; // U+E1F0 Turks & Caicos Islands
    const constexpr char ICON_TD[]     = "\xEE\x87\xB1"; // U+E1F1 Chad
    const constexpr char ICON_TF[]     = "\xEE\x87\xB3"; // U+E1F3 French Southern Territories
    const constexpr char ICON_TG[]     = "\xEE\x87\xB4"; // U+E1F4 Togo
    const constexpr char ICON_TH[]     = "\xEE\x87\xB5"; // U+E1F5 Thailand
    const constexpr char ICON_TJ[]     = "\xEE\x87\xB7"; // U+E1F7 Tajikistan
    const constexpr char ICON_TK[]     = "\xEE\x87\xB8"; // U+E1F8 Tokelau
    const constexpr char ICON_TL[]     = "\xEE\x87\xB9"; // U+E1F9 Timor-Leste
    const constexpr char ICON_TM[]     = "\xEE\x87\xBA"; // U+E1FA Turkmenistan
    const constexpr char ICON_TN[]     = "\xEE\x87\xBB"; // U+E1FB Tunisia
    const constexpr char ICON_TO[]     = "\xEE\x87\xBC"; // U+E1FC Tonga
    const constexpr char ICON_TR[]     = "\xEE\x87\xBF"; // U+E1FF Türkiye
    const constexpr char ICON_TT[]     = "\xEE\x88\x81"; // U+E201 Trinidad & Tobago
    const constexpr char ICON_TV[]     = "\xEE\x88\x83"; // U+E203 Tuvalu
    const constexpr char ICON_TW[]     = "\xEE\x88\x84"; // U+E204 Taiwan
    const constexpr char ICON_TZ[]     = "\xEE\x88\x87"; // U+E207 Tanzania
    const constexpr char ICON_UA[]     = "\xEE\x88\x88"; // U+E208 Ukraine
    const constexpr char ICON_UG[]     = "\xEE\x88\x8E"; // U+E20E Uganda
    const constexpr char ICON_UM[]     = "\xEE\x88\x94"; // U+E214 U.S. Outlying Islands
    const constexpr char ICON_UN[]     = "\xEE\x88\x95"; // U+E215 United Nations
    const constexpr char ICON_US[]     = "\xEE\x88\x9A"; // U+E21A United States
    const constexpr char ICON_UY[]     = "\xEE\x88\xA0"; // U+E220 Uruguay
    const constexpr char ICON_UZ[]     = "\xEE\x88\xA1"; // U+E221 Uzbekistan
    const constexpr char ICON_VA[]     = "\xEE\x88\xA2"; // U+E222 Vatican City
    const constexpr char ICON_VC[]     = "\xEE\x88\xA4"; // U+E224 St. Vincent & Grenadines
    const constexpr char ICON_VE[]     = "\xEE\x88\xA6"; // U+E226 Venezuela
    const constexpr char ICON_VG[]     = "\xEE\x88\xA8"; // U+E228 British Virgin Islands
    const constexpr char ICON_VI[]     = "\xEE\x88\xAA"; // U+E22A U.S. Virgin Islands
    const constexpr char ICON_VN[]     = "\xEE\x88\xAF"; // U+E22F Vietnam
    const constexpr char ICON_VU[]     = "\xEE\x88\xB6"; // U+E236 Vanuatu
    const constexpr char ICON_WF[]     = "\xEE\x89\x81"; // U+E241 Wallis & Futuna
    const constexpr char ICON_WS[]     = "\xEE\x89\x8E"; // U+E24E Samoa
    const constexpr char ICON_XK[]     = "\xEE\x89\xA0"; // U+E260 Kosovo
    const constexpr char ICON_YE[]     = "\xEE\x89\xB4"; // U+E274 Yemen
    const constexpr char ICON_YT[]     = "\xEE\x8A\x83"; // U+E283 Mayotte
    const constexpr char ICON_YU[]     = "\xEE\x8A\x84";
    const constexpr char ICON_ZA[]     = "\xEE\x8A\x8A"; // U+E28A South Africa
    const constexpr char ICON_ZM[]     = "\xEE\x8A\x96"; // U+E296 Zambia
    const constexpr char ICON_ZW[]     = "\xEE\x8A\xA0"; // U+E2A0 Zimbabwe
    const constexpr char ICON_MR_OLD[] = "\xEE\x8A\xB0";
    const constexpr char ICON_HN_OLD[] = "\xEE\x8A\xB1";
    const constexpr char ICON_SY_OLD[] = "\xEE\x8A\xB2";
    const constexpr char ICON_AUSTRALIAN_ABORIGINAL_FLAG[] = "\xEE\x8B\x80";
    const constexpr char ICON_REFUGEE_NATION_FLAG[]        = "\xEE\x8B\x81";
    const constexpr char ICON_PIRATE_FLAG[]                = "\xEE\x8B\xA0";
    const constexpr char ICON_RAINBOW_FLAG[]               = "\xEE\x8B\xB0";
    const constexpr char ICON_TRANSGENDER_FLAG[]           = "\xEE\x8B\xB1";
    const constexpr char ICON_AT_1[]                       = "\xEE\x8C\x80";
    const constexpr char ICON_AT_2[]                       = "\xEE\x8C\x81";
    const constexpr char ICON_AT_3[]                       = "\xEE\x8C\x82";
    const constexpr char ICON_AT_4[]                       = "\xEE\x8C\x83";
    const constexpr char ICON_AT_5[]                       = "\xEE\x8C\x84";
    const constexpr char ICON_AT_6[]                       = "\xEE\x8C\x85";
    const constexpr char ICON_AT_7[]                       = "\xEE\x8C\x86";
    const constexpr char ICON_AT_8[]                       = "\xEE\x8C\x87";
    const constexpr char ICON_AT_9[]                       = "\xEE\x8C\x88";
    const constexpr char ICON_BE_BRU[]                     = "\xEE\x8C\x90";
    const constexpr char ICON_BE_VLG[]                     = "\xEE\x8C\x91";
    const constexpr char ICON_BE_WAL[]                     = "\xEE\x8C\x92";
    const constexpr char ICON_BQ_BO[]                      = "\xEE\x8C\xA0";
    const constexpr char ICON_BQ_SA[]                      = "\xEE\x8C\xA1";
    const constexpr char ICON_BQ_SE[]                      = "\xEE\x8C\xA2";
    const constexpr char ICON_CA_NL[]                      = "\xEE\x8C\xB0";
    const constexpr char ICON_CA_NU[]                      = "\xEE\x8C\xB1";
    const constexpr char ICON_CA_QC[]                      = "\xEE\x8C\xB2";
    const constexpr char ICON_CH_FR[]                      = "\xEE\x8D\x80";
    const constexpr char ICON_CH_LU[]                      = "\xEE\x8D\x81";
    const constexpr char ICON_CH_NE[]                      = "\xEE\x8D\x82";
    const constexpr char ICON_CH_SO[]                      = "\xEE\x8D\x83";
    const constexpr char ICON_CH_SZ[]                      = "\xEE\x8D\x84";
    const constexpr char ICON_CH_TI[]                      = "\xEE\x8D\x85";
    const constexpr char ICON_CH_VS[]                      = "\xEE\x8D\x86";
    const constexpr char ICON_CH_ZG[]                      = "\xEE\x8D\x87";
    const constexpr char ICON_CH_ZH[]                      = "\xEE\x8D\x88";
    const constexpr char ICON_DE_BY[]                      = "\xEE\x8D\xA0";
    const constexpr char ICON_DE_BY_ALT1[]                 = "\xEE\x8D\xA1";
    const constexpr char ICON_ES_CT[]                      = "\xEE\x8D\xB0";
    const constexpr char ICON_ES_PV[]                      = "\xEE\x8D\xB1";
    const constexpr char ICON_FR_BRE[]                     = "\xEE\x8E\x80";
    const constexpr char ICON_GB_AGY[]                     = "\xEE\x8E\x90";
    const constexpr char ICON_GB_CON[]                     = "\xEE\x8E\x91";
    const constexpr char ICON_GB_DEV[]                     = "\xEE\x8E\x92";
    const constexpr char ICON_GB_DOR[]                     = "\xEE\x8E\x93";
    const constexpr char ICON_GB_ENG[]                     = "\xEE\x8E\x94";
    const constexpr char ICON_GB_FLN[]                     = "\xEE\x8E\x95";
    const constexpr char ICON_GB_MON[]                     = "\xEE\x8E\x96";
    const constexpr char ICON_GB_NBL[]                     = "\xEE\x8E\x97";
    const constexpr char ICON_GB_NIR[]                     = "\xEE\x8E\x98";
    const constexpr char ICON_GB_ORK[]                     = "\xEE\x8E\x99";
    const constexpr char ICON_GB_PEM[]                     = "\xEE\x8E\x9A";
    const constexpr char ICON_GB_SCT[]                     = "\xEE\x8E\x9B";
    const constexpr char ICON_GB_SRY[]                     = "\xEE\x8E\x9C";
    const constexpr char ICON_GB_VGL[]                     = "\xEE\x8E\x9D";
    const constexpr char ICON_GB_WLS[]                     = "\xEE\x8E\x9E";
    const constexpr char ICON_GB_XBR[]                     = "\xEE\x8E\x9F";
    const constexpr char ICON_GB_XCA[]                     = "\xEE\x8E\xA0";
    const constexpr char ICON_GB_XCR[]                     = "\xEE\x8E\xA1";
    const constexpr char ICON_GB_XKD[]                     = "\xEE\x8E\xA2";
    const constexpr char ICON_GB_XME[]                     = "\xEE\x8E\xA3";
    const constexpr char ICON_GB_ZET[]                     = "\xEE\x8E\xA4";
    const constexpr char ICON_IE_C[]                       = "\xEE\x8F\x80";
    const constexpr char ICON_IE_L[]                       = "\xEE\x8F\x81";
    const constexpr char ICON_IE_M[]                       = "\xEE\x8F\x82";
    const constexpr char ICON_IE_U[]                       = "\xEE\x8F\x83";
    const constexpr char ICON_IQ_KR[]                      = "\xEE\x8F\x90";
    const constexpr char ICON_NL_FR[]                      = "\xEE\x8F\xA0";
    const constexpr char ICON_US_AK[]                      = "\xEE\x90\x80";
    const constexpr char ICON_US_AL[]                      = "\xEE\x90\x81";
    const constexpr char ICON_US_AZ[]                      = "\xEE\x90\x82";
    const constexpr char ICON_US_CA[]                      = "\xEE\x90\x83";
    const constexpr char ICON_US_CO[]                      = "\xEE\x90\x84";
    const constexpr char ICON_US_DC[]                      = "\xEE\x90\x85";
    const constexpr char ICON_US_HI[]                      = "\xEE\x90\x86";
    const constexpr char ICON_US_IN[]                      = "\xEE\x90\x87";
    const constexpr char ICON_US_MD[]                      = "\xEE\x90\x88";
    const constexpr char ICON_US_NM[]                      = "\xEE\x90\x89";
    const constexpr char ICON_US_SC[]                      = "\xEE\x90\x8A";
    const constexpr char ICON_US_TN[]                      = "\xEE\x90\x8B";
    const constexpr char ICON_US_TX[]                      = "\xEE\x90\x8C";

    // ----- -----

    const constexpr char ICON_ANDORRA[]                                  = "\xEE\x80\x83"; // U+E003 AD
    const constexpr char ICON_UNITED_ARAB_EMIRATES[]                     = "\xEE\x80\x84"; // U+E004 AE
    const constexpr char ICON_AFGHANISTAN[]                              = "\xEE\x80\x85"; // U+E005 AF
    const constexpr char ICON_ANTIGUA_AND_BARBUDA[]                      = "\xEE\x80\x86"; // U+E006 AG
    const constexpr char ICON_ANGUILLA[]                                 = "\xEE\x80\x88"; // U+E008 AI
    const constexpr char ICON_ALBANIA[]                                  = "\xEE\x80\x8B"; // U+E00B AL
    const constexpr char ICON_ARMENIA[]                                  = "\xEE\x80\x8C"; // U+E00C AM
    const constexpr char ICON_ANGOLA[]                                   = "\xEE\x80\x8E"; // U+E00E AO
    const constexpr char ICON_ANTARCTICA[]                               = "\xEE\x80\x90"; // U+E010 AQ
    const constexpr char ICON_ARGENTINA[]                                = "\xEE\x80\x91"; // U+E011 AR
    const constexpr char ICON_AMERICAN_SAMOA[]                           = "\xEE\x80\x92"; // U+E012 AS
    const constexpr char ICON_AUSTRIA[]                                  = "\xEE\x80\x93"; // U+E013 AT
    const constexpr char ICON_AUSTRALIA[]                                = "\xEE\x80\x94"; // U+E014 AU
    const constexpr char ICON_ARUBA[]                                    = "\xEE\x80\x96"; // U+E016 AW
    const constexpr char ICON_ÅLAND_ISLANDS[]                            = "\xEE\x80\x97"; // U+E017 AX
    const constexpr char ICON_AZERBAIJAN[]                               = "\xEE\x80\x99"; // U+E019 AZ
    const constexpr char ICON_BOSNIA_AND_HERZEGOVINA[]                   = "\xEE\x80\x9A"; // U+E01A BA
    const constexpr char ICON_BARBADOS[]                                 = "\xEE\x80\x9B"; // U+E01B BB
    const constexpr char ICON_BANGLADESH[]                               = "\xEE\x80\x9D"; // U+E01D BD
    const constexpr char ICON_BELGIUM[]                                  = "\xEE\x80\x9E"; // U+E01E BE
    const constexpr char ICON_BURKINA_FASO[]                             = "\xEE\x80\x9F"; // U+E01F BF
    const constexpr char ICON_BULGARIA[]                                 = "\xEE\x80\xA0"; // U+E020 BG
    const constexpr char ICON_BAHRAIN[]                                  = "\xEE\x80\xA1"; // U+E021 BH
    const constexpr char ICON_BURUNDI[]                                  = "\xEE\x80\xA2"; // U+E022 BI
    const constexpr char ICON_BENIN[]                                    = "\xEE\x80\xA3"; // U+E023 BJ
    const constexpr char ICON_ST_BARTHÉLEMY[]                            = "\xEE\x80\xA5"; // U+E025 BL
    const constexpr char ICON_BERMUDA[]                                  = "\xEE\x80\xA6"; // U+E026 BM
    const constexpr char ICON_BRUNEI[]                                   = "\xEE\x80\xA7"; // U+E027 BN
    const constexpr char ICON_BOLIVIA[]                                  = "\xEE\x80\xA8"; // U+E028 BO
    const constexpr char ICON_CARIBBEAN_NETHERLANDS[]                    = "\xEE\x80\xAA"; // U+E02A BQ
    const constexpr char ICON_BRAZIL[]                                   = "\xEE\x80\xAB"; // U+E02B BR
    const constexpr char ICON_BAHAMAS[]                                  = "\xEE\x80\xAC"; // U+E02C BS
    const constexpr char ICON_BHUTAN[]                                   = "\xEE\x80\xAD"; // U+E02D BT
    const constexpr char ICON_BOUVET_ISLAND[]                            = "\xEE\x80\xAF"; // U+E02F BV
    const constexpr char ICON_BOTSWANA[]                                 = "\xEE\x80\xB0"; // U+E030 BW
    const constexpr char ICON_BELARUS[]                                  = "\xEE\x80\xB2"; // U+E032 BY
    const constexpr char ICON_BELIZE[]                                   = "\xEE\x80\xB3"; // U+E033 BZ
    const constexpr char ICON_CANADA[]                                   = "\xEE\x80\xB4"; // U+E034 CA
    const constexpr char ICON_COCOS_KEELING_ISLANDS[]                    = "\xEE\x80\xB6"; // U+E036 CC
    const constexpr char ICON_CONGO_KINSHASA[]                           = "\xEE\x80\xB7"; // U+E037 CD
    const constexpr char ICON_CENTRAL_AFRICAN_REPUBLIC[]                 = "\xEE\x80\xB9"; // U+E039 CF
    const constexpr char ICON_CONGO_BRAZZAVILLE[]                        = "\xEE\x80\xBA"; // U+E03A CG
    const constexpr char ICON_SWITZERLAND[]                              = "\xEE\x80\xBB"; // U+E03B CH
    const constexpr char ICON_CÔTE_DIVOIRE[]                             = "\xEE\x80\xBC"; // U+E03C CI
    const constexpr char ICON_COOK_ISLANDS[]                             = "\xEE\x80\xBE"; // U+E03E CK
    const constexpr char ICON_CHILE[]                                    = "\xEE\x80\xBF"; // U+E03F CL
    const constexpr char ICON_CAMEROON[]                                 = "\xEE\x81\x80"; // U+E040 CM
    const constexpr char ICON_CHINA[]                                    = "\xEE\x81\x81"; // U+E041 CN
    const constexpr char ICON_COLOMBIA[]                                 = "\xEE\x81\x82"; // U+E042 CO
    const constexpr char ICON_CLIPPERTON_ISLAND[]                        = "\xEE\x81\x83"; // U+E043 CP
    const constexpr char ICON_SARK[]                                     = "\xEE\x81\x84"; // U+E044 CQ
    const constexpr char ICON_COSTA_RICA[]                               = "\xEE\x81\x85"; // U+E045 CR
    const constexpr char ICON_CUBA[]                                     = "\xEE\x81\x88"; // U+E048 CU
    const constexpr char ICON_CAPE_VERDE[]                               = "\xEE\x81\x89"; // U+E049 CV
    const constexpr char ICON_CURAÇAO[]                                  = "\xEE\x81\x8A"; // U+E04A CW
    const constexpr char ICON_CHRISTMAS_ISLAND[]                         = "\xEE\x81\x8B"; // U+E04B CX
    const constexpr char ICON_CYPRUS[]                                   = "\xEE\x81\x8C"; // U+E04C CY
    const constexpr char ICON_CZECHIA[]                                  = "\xEE\x81\x8D"; // U+E04D CZ
    const constexpr char ICON_GERMANY[]                                  = "\xEE\x81\x92"; // U+E052 DE
    const constexpr char ICON_DJIBOUTI[]                                 = "\xEE\x81\x97"; // U+E057 DJ
    const constexpr char ICON_DENMARK[]                                  = "\xEE\x81\x98"; // U+E058 DK
    const constexpr char ICON_DOMINICA[]                                 = "\xEE\x81\x9A"; // U+E05A DM
    const constexpr char ICON_DOMINICAN_REPUBLIC[]                       = "\xEE\x81\x9C"; // U+E05C DO
    const constexpr char ICON_ALGERIA[]                                  = "\xEE\x81\xA7"; // U+E067 DZ
    const constexpr char ICON_ECUADOR[]                                  = "\xEE\x81\xAA"; // U+E06A EC
    const constexpr char ICON_ESTONIA[]                                  = "\xEE\x81\xAC"; // U+E06C EE
    const constexpr char ICON_EGYPT[]                                    = "\xEE\x81\xAE"; // U+E06E EG
    const constexpr char ICON_WESTERN_SAHARA[]                           = "\xEE\x81\xAF"; // U+E06F EH
    const constexpr char ICON_ERITREA[]                                  = "\xEE\x81\xB9"; // U+E079 ER
    const constexpr char ICON_SPAIN[]                                    = "\xEE\x81\xBA"; // U+E07A ES
    const constexpr char ICON_ETHIOPIA[]                                 = "\xEE\x81\xBB"; // U+E07B ET
    const constexpr char ICON_EUROPEAN_UNION[]                           = "\xEE\x81\xBC"; // U+E07C EU
    const constexpr char ICON_FINLAND[]                                  = "\xEE\x82\x8A"; // U+E08A FI
    const constexpr char ICON_FIJI[]                                     = "\xEE\x82\x8B"; // U+E08B FJ
    const constexpr char ICON_FALKLAND_ISLANDS[]                         = "\xEE\x82\x8C"; // U+E08C FK
    const constexpr char ICON_MICRONESIA[]                               = "\xEE\x82\x8E"; // U+E08E FM
    const constexpr char ICON_FAROE_ISLANDS[]                            = "\xEE\x82\x90"; // U+E090 FO
    const constexpr char ICON_FRANCE[]                                   = "\xEE\x82\x93"; // U+E093 FR
    const constexpr char ICON_GABON[]                                    = "\xEE\x82\x9C"; // U+E09C GA
    const constexpr char ICON_UNITED_KINGDOM[]                           = "\xEE\x82\x9D"; // U+E09D GB
    const constexpr char ICON_GRENADA[]                                  = "\xEE\x82\x9F"; // U+E09F GD
    const constexpr char ICON_GEORGIA[]                                  = "\xEE\x82\xA0"; // U+E0A0 GE
    const constexpr char ICON_FRENCH_GUIANA[]                            = "\xEE\x82\xA1"; // U+E0A1 GF
    const constexpr char ICON_GUERNSEY[]                                 = "\xEE\x82\xA2"; // U+E0A2 GG
    const constexpr char ICON_GHANA[]                                    = "\xEE\x82\xA3"; // U+E0A3 GH
    const constexpr char ICON_GIBRALTAR[]                                = "\xEE\x82\xA4"; // U+E0A4 GI
    const constexpr char ICON_GREENLAND[]                                = "\xEE\x82\xA7"; // U+E0A7 GL
    const constexpr char ICON_GAMBIA[]                                   = "\xEE\x82\xA8"; // U+E0A8 GM
    const constexpr char ICON_GUINEA[]                                   = "\xEE\x82\xA9"; // U+E0A9 GN
    const constexpr char ICON_GUADELOUPE[]                               = "\xEE\x82\xAB"; // U+E0AB GP
    const constexpr char ICON_EQUATORIAL_GUINEA[]                        = "\xEE\x82\xAC"; // U+E0AC GQ
    const constexpr char ICON_GREECE[]                                   = "\xEE\x82\xAD"; // U+E0AD GR
    const constexpr char ICON_SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS[] = "\xEE\x82\xAE"; // U+E0AE GS
    const constexpr char ICON_GUATEMALA[]                                = "\xEE\x82\xAF"; // U+E0AF GT
    const constexpr char ICON_GUAM[]                                     = "\xEE\x82\xB0"; // U+E0B0 GU
    const constexpr char ICON_GUINEA_BISSAU[]                            = "\xEE\x82\xB2"; // U+E0B2 GW
    const constexpr char ICON_GUYANA[]                                   = "\xEE\x82\xB4"; // U+E0B4 GY
    const constexpr char ICON_HONG_KONG_SAR_CHINA[]                      = "\xEE\x83\x80"; // U+E0C0 HK
    const constexpr char ICON_HEARD_AND_MCDONALD_ISLANDS[]               = "\xEE\x83\x82"; // U+E0C2 HM
    const constexpr char ICON_HONDURAS[]                                 = "\xEE\x83\x83"; // U+E0C3 HN
    const constexpr char ICON_CROATIA[]                                  = "\xEE\x83\x87"; // U+E0C7 HR
    const constexpr char ICON_HAITI[]                                    = "\xEE\x83\x89"; // U+E0C9 HT
    const constexpr char ICON_HUNGARY[]                                  = "\xEE\x83\x8A"; // U+E0CA HU
    const constexpr char ICON_INDONESIA[]                                = "\xEE\x83\x93"; // U+E0D3 ID
    const constexpr char ICON_IRELAND[]                                  = "\xEE\x83\x94"; // U+E0D4 IE
    const constexpr char ICON_ISRAEL[]                                   = "\xEE\x83\x9B"; // U+E0DB IL
    const constexpr char ICON_ISLE_OF_MAN[]                              = "\xEE\x83\x9C"; // U+E0DC IM
    const constexpr char ICON_INDIA[]                                    = "\xEE\x83\x9D"; // U+E0DD IN
    const constexpr char ICON_BRITISH_INDIAN_OCEAN_TERRITORY[]           = "\xEE\x83\x9E"; // U+E0DE IO
    const constexpr char ICON_IRAQ[]                                     = "\xEE\x83\xA0"; // U+E0E0 IQ
    const constexpr char ICON_IRAN[]                                     = "\xEE\x83\xA1"; // U+E0E1 IR
    const constexpr char ICON_ICELAND[]                                  = "\xEE\x83\xA2"; // U+E0E2 IS
    const constexpr char ICON_ITALY[]                                    = "\xEE\x83\xA3"; // U+E0E3 IT
    const constexpr char ICON_JERSEY[]                                   = "\xEE\x83\xAE"; // U+E0EE JE
    const constexpr char ICON_JAMAICA[]                                  = "\xEE\x83\xB6"; // U+E0F6 JM
    const constexpr char ICON_JORDAN[]                                   = "\xEE\x83\xB8"; // U+E0F8 JO
    const constexpr char ICON_JAPAN[]                                    = "\xEE\x83\xB9"; // U+E0F9 JP
    const constexpr char ICON_KENYA[]                                    = "\xEE\x84\x88"; // U+E108 KE
    const constexpr char ICON_KYRGYZSTAN[]                               = "\xEE\x84\x8A"; // U+E10A KG
    const constexpr char ICON_CAMBODIA[]                                 = "\xEE\x84\x8B"; // U+E10B KH
    const constexpr char ICON_KIRIBATI[]                                 = "\xEE\x84\x8C"; // U+E10C KI
    const constexpr char ICON_COMOROS[]                                  = "\xEE\x84\x90"; // U+E110 KM
    const constexpr char ICON_ST_KITTS_AND_NEVIS[]                       = "\xEE\x84\x91"; // U+E111 KN
    const constexpr char ICON_NORTH_KOREA[]                              = "\xEE\x84\x93"; // U+E113 KP
    const constexpr char ICON_SOUTH_KOREA[]                              = "\xEE\x84\x95"; // U+E115 KR
    const constexpr char ICON_KUWAIT[]                                   = "\xEE\x84\x9A"; // U+E11A KW
    const constexpr char ICON_CAYMAN_ISLANDS[]                           = "\xEE\x84\x9C"; // U+E11C KY
    const constexpr char ICON_KAZAKHSTAN[]                               = "\xEE\x84\x9D"; // U+E11D KZ
    const constexpr char ICON_LAOS[]                                     = "\xEE\x84\x9E"; // U+E11E LA
    const constexpr char ICON_LEBANON[]                                  = "\xEE\x84\x9F"; // U+E11F LB
    const constexpr char ICON_ST_LUCIA[]                                 = "\xEE\x84\xA0"; // U+E120 LC
    const constexpr char ICON_LIECHTENSTEIN[]                            = "\xEE\x84\xA6"; // U+E126 LI
    const constexpr char ICON_SRI_LANKA[]                                = "\xEE\x84\xA8"; // U+E128 LK
    const constexpr char ICON_LIBERIA[]                                  = "\xEE\x84\xAF"; // U+E12F LR
    const constexpr char ICON_LESOTHO[]                                  = "\xEE\x84\xB0"; // U+E130 LS
    const constexpr char ICON_LITHUANIA[]                                = "\xEE\x84\xB1"; // U+E131 LT
    const constexpr char ICON_LUXEMBOURG[]                               = "\xEE\x84\xB2"; // U+E132 LU
    const constexpr char ICON_LATVIA[]                                   = "\xEE\x84\xB3"; // U+E133 LV
    const constexpr char ICON_LIBYA[]                                    = "\xEE\x84\xB6"; // U+E136 LY
    const constexpr char ICON_MOROCCO[]                                  = "\xEE\x84\xB8"; // U+E138 MA
    const constexpr char ICON_MONACO[]                                   = "\xEE\x84\xBA"; // U+E13A MC
    const constexpr char ICON_MOLDOVA[]                                  = "\xEE\x84\xBB"; // U+E13B MD
    const constexpr char ICON_MONTENEGRO[]                               = "\xEE\x84\xBC"; // U+E13C ME
    const constexpr char ICON_ST_MARTIN[]                                = "\xEE\x84\xBD"; // U+E13D MF
    const constexpr char ICON_MADAGASCAR[]                               = "\xEE\x84\xBE"; // U+E13E MG
    const constexpr char ICON_MARSHALL_ISLANDS[]                         = "\xEE\x84\xBF"; // U+E13F MH
    const constexpr char ICON_NORTH_MACEDONIA[]                          = "\xEE\x85\x82"; // U+E142 MK
    const constexpr char ICON_MALI[]                                     = "\xEE\x85\x83"; // U+E143 ML
    const constexpr char ICON_MYANMAR_BURMA[]                            = "\xEE\x85\x84"; // U+E144 MM
    const constexpr char ICON_MONGOLIA[]                                 = "\xEE\x85\x85"; // U+E145 MN
    const constexpr char ICON_MACAO_SAR_CHINA[]                          = "\xEE\x85\x86"; // U+E146 MO
    const constexpr char ICON_NORTHERN_MARIANA_ISLANDS[]                 = "\xEE\x85\x87"; // U+E147 MP
    const constexpr char ICON_MARTINIQUE[]                               = "\xEE\x85\x88"; // U+E148 MQ
    const constexpr char ICON_MAURITANIA[]                               = "\xEE\x85\x89"; // U+E149 MR
    const constexpr char ICON_MONTSERRAT[]                               = "\xEE\x85\x8A"; // U+E14A MS
    const constexpr char ICON_MALTA[]                                    = "\xEE\x85\x8B"; // U+E14B MT
    const constexpr char ICON_MAURITIUS[]                                = "\xEE\x85\x8C"; // U+E14C MU
    const constexpr char ICON_MALDIVES[]                                 = "\xEE\x85\x8D"; // U+E14D MV
    const constexpr char ICON_MALAWI[]                                   = "\xEE\x85\x8E"; // U+E14E MW
    const constexpr char ICON_MEXICO[]                                   = "\xEE\x85\x8F"; // U+E14F MX
    const constexpr char ICON_MALAYSIA[]                                 = "\xEE\x85\x90"; // U+E150 MY
    const constexpr char ICON_MOZAMBIQUE[]                               = "\xEE\x85\x91"; // U+E151 MZ
    const constexpr char ICON_NAMIBIA[]                                  = "\xEE\x85\x92"; // U+E152 NA
    const constexpr char ICON_NEW_CALEDONIA[]                            = "\xEE\x85\x94"; // U+E154 NC
    const constexpr char ICON_NIGER[]                                    = "\xEE\x85\x96"; // U+E156 NE
    const constexpr char ICON_NORFOLK_ISLAND[]                           = "\xEE\x85\x97"; // U+E157 NF
    const constexpr char ICON_NIGERIA[]                                  = "\xEE\x85\x98"; // U+E158 NG
    const constexpr char ICON_NICARAGUA[]                                = "\xEE\x85\x9A"; // U+E15A NI
    const constexpr char ICON_NETHERLANDS[]                              = "\xEE\x85\x9D"; // U+E15D NL
    const constexpr char ICON_NORWAY[]                                   = "\xEE\x85\xA0"; // U+E160 NO
    const constexpr char ICON_NEPAL[]                                    = "\xEE\x85\xA1"; // U+E161 NP
    const constexpr char ICON_NAURU[]                                    = "\xEE\x85\xA3"; // U+E163 NR
    const constexpr char ICON_NIUE[]                                     = "\xEE\x85\xA6"; // U+E166 NU
    const constexpr char ICON_NEW_ZEALAND[]                              = "\xEE\x85\xAB"; // U+E16B NZ
    const constexpr char ICON_OMAN[]                                     = "\xEE\x85\xB8"; // U+E178 OM
    const constexpr char ICON_PANAMA[]                                   = "\xEE\x86\x86"; // U+E186 PA
    const constexpr char ICON_PERU[]                                     = "\xEE\x86\x8A"; // U+E18A PE
    const constexpr char ICON_FRENCH_POLYNESIA[]                         = "\xEE\x86\x8B"; // U+E18B PF
    const constexpr char ICON_PAPUA_NEW_GUINEA[]                         = "\xEE\x86\x8C"; // U+E18C PG
    const constexpr char ICON_PHILIPPINES[]                              = "\xEE\x86\x8D"; // U+E18D PH
    const constexpr char ICON_PAKISTAN[]                                 = "\xEE\x86\x90"; // U+E190 PK
    const constexpr char ICON_POLAND[]                                   = "\xEE\x86\x91"; // U+E191 PL
    const constexpr char ICON_ST_PIERRE_AND_MIQUELON[]                   = "\xEE\x86\x92"; // U+E192 PM
    const constexpr char ICON_PITCAIRN_ISLANDS[]                         = "\xEE\x86\x93"; // U+E193 PN
    const constexpr char ICON_PUERTO_RICO[]                              = "\xEE\x86\x97"; // U+E197 PR
    const constexpr char ICON_PALESTINIAN_TERRITORIES[]                  = "\xEE\x86\x98"; // U+E198 PS
    const constexpr char ICON_PORTUGAL[]                                 = "\xEE\x86\x99"; // U+E199 PT
    const constexpr char ICON_PALAU[]                                    = "\xEE\x86\x9C"; // U+E19C PW
    const constexpr char ICON_PARAGUAY[]                                 = "\xEE\x86\x9E"; // U+E19E PY
    const constexpr char ICON_QATAR[]                                    = "\xEE\x86\xA0"; // U+E1A0 QA
    const constexpr char ICON_RÉUNION[]                                  = "\xEE\x86\xBE"; // U+E1BE RE
    const constexpr char ICON_ROMANIA[]                                  = "\xEE\x87\x88"; // U+E1C8 RO
    const constexpr char ICON_SERBIA[]                                   = "\xEE\x87\x8C"; // U+E1CC RS
    const constexpr char ICON_RUSSIA[]                                   = "\xEE\x87\x8E"; // U+E1CE RU
    const constexpr char ICON_RWANDA[]                                   = "\xEE\x87\x90"; // U+E1D0 RW
    const constexpr char ICON_SAUDI_ARABIA[]                             = "\xEE\x87\x94"; // U+E1D4 SA
    const constexpr char ICON_SOLOMON_ISLANDS[]                          = "\xEE\x87\x95"; // U+E1D5 SB
    const constexpr char ICON_SEYCHELLES[]                               = "\xEE\x87\x96"; // U+E1D6 SC
    const constexpr char ICON_SUDAN[]                                    = "\xEE\x87\x97"; // U+E1D7 SD
    const constexpr char ICON_SWEDEN[]                                   = "\xEE\x87\x98"; // U+E1D8 SE
    const constexpr char ICON_SINGAPORE[]                                = "\xEE\x87\x9A"; // U+E1DA SG
    const constexpr char ICON_ST_HELENA[]                                = "\xEE\x87\x9B"; // U+E1DB SH
    const constexpr char ICON_SLOVENIA[]                                 = "\xEE\x87\x9C"; // U+E1DC SI
    const constexpr char ICON_SVALBARD_AND_JAN_MAYEN[]                   = "\xEE\x87\x9D"; // U+E1DD SJ
    const constexpr char ICON_SLOVAKIA[]                                 = "\xEE\x87\x9E"; // U+E1DE SK
    const constexpr char ICON_SIERRA_LEONE[]                             = "\xEE\x87\x9F"; // U+E1DF SL
    const constexpr char ICON_SAN_MARINO[]                               = "\xEE\x87\xA0"; // U+E1E0 SM
    const constexpr char ICON_SENEGAL[]                                  = "\xEE\x87\xA1"; // U+E1E1 SN
    const constexpr char ICON_SOMALIA[]                                  = "\xEE\x87\xA2"; // U+E1E2 SO
    const constexpr char ICON_SURINAME[]                                 = "\xEE\x87\xA5"; // U+E1E5 SR
    const constexpr char ICON_SOUTH_SUDAN[]                              = "\xEE\x87\xA6"; // U+E1E6 SS
    const constexpr char ICON_SÃO_TOMÉ_AND_PRÍNCIPE[]                    = "\xEE\x87\xA7"; // U+E1E7 ST
    const constexpr char ICON_EL_SALVADOR[]                              = "\xEE\x87\xA9"; // U+E1E9 SV
    const constexpr char ICON_SINT_MAARTEN[]                             = "\xEE\x87\xAB"; // U+E1EB SX
    const constexpr char ICON_SYRIA[]                                    = "\xEE\x87\xAC"; // U+E1EC SY
    const constexpr char ICON_ESWATINI[]                                 = "\xEE\x87\xAD"; // U+E1ED SZ
    const constexpr char ICON_TURKS_AND_CAICOS_ISLANDS[]                 = "\xEE\x87\xB0"; // U+E1F0 TC
    const constexpr char ICON_CHAD[]                                     = "\xEE\x87\xB1"; // U+E1F1 TD
    const constexpr char ICON_FRENCH_SOUTHERN_TERRITORIES[]              = "\xEE\x87\xB3"; // U+E1F3 TF
    const constexpr char ICON_TOGO[]                                     = "\xEE\x87\xB4"; // U+E1F4 TG
    const constexpr char ICON_THAILAND[]                                 = "\xEE\x87\xB5"; // U+E1F5 TH
    const constexpr char ICON_TAJIKISTAN[]                               = "\xEE\x87\xB7"; // U+E1F7 TJ
    const constexpr char ICON_TOKELAU[]                                  = "\xEE\x87\xB8"; // U+E1F8 TK
    const constexpr char ICON_TIMOR_LESTE[]                              = "\xEE\x87\xB9"; // U+E1F9 TL
    const constexpr char ICON_TURKMENISTAN[]                             = "\xEE\x87\xBA"; // U+E1FA TM
    const constexpr char ICON_TUNISIA[]                                  = "\xEE\x87\xBB"; // U+E1FB TN
    const constexpr char ICON_TONGA[]                                    = "\xEE\x87\xBC"; // U+E1FC TO
    const constexpr char ICON_TÜRKIYE[]                                  = "\xEE\x87\xBF"; // U+E1FF TR
    const constexpr char ICON_TRINIDAD_AND_TOBAGO[]                      = "\xEE\x88\x81"; // U+E201 TT
    const constexpr char ICON_TUVALU[]                                   = "\xEE\x88\x83"; // U+E203 TV
    const constexpr char ICON_TAIWAN[]                                   = "\xEE\x88\x84"; // U+E204 TW
    const constexpr char ICON_TANZANIA[]                                 = "\xEE\x88\x87"; // U+E207 TZ
    const constexpr char ICON_UKRAINE[]                                  = "\xEE\x88\x88"; // U+E208 UA
    const constexpr char ICON_UGANDA[]                                   = "\xEE\x88\x8E"; // U+E20E UG
    const constexpr char ICON_US_OUTLYING_ISLANDS[]                      = "\xEE\x88\x94"; // U+E214 UM
    const constexpr char ICON_UNITED_NATIONS[]                           = "\xEE\x88\x95"; // U+E215 UN
    const constexpr char ICON_UNITED_STATES[]                            = "\xEE\x88\x9A"; // U+E21A US
    const constexpr char ICON_URUGUAY[]                                  = "\xEE\x88\xA0"; // U+E220 UY
    const constexpr char ICON_UZBEKISTAN[]                               = "\xEE\x88\xA1"; // U+E221 UZ
    const constexpr char ICON_VATICAN_CITY[]                             = "\xEE\x88\xA2"; // U+E222 VA
    const constexpr char ICON_ST_VINCENT_AND_GRENADINES[]                = "\xEE\x88\xA4"; // U+E224 VC
    const constexpr char ICON_VENEZUELA[]                                = "\xEE\x88\xA6"; // U+E226 VE
    const constexpr char ICON_BRITISH_VIRGIN_ISLANDS[]                   = "\xEE\x88\xA8"; // U+E228 VG
    const constexpr char ICON_US_VIRGIN_ISLANDS[]                        = "\xEE\x88\xAA"; // U+E22A VI
    const constexpr char ICON_VIETNAM[]                                  = "\xEE\x88\xAF"; // U+E22F VN
    const constexpr char ICON_VANUATU[]                                  = "\xEE\x88\xB6"; // U+E236 VU
    const constexpr char ICON_WALLIS_AND_FUTUNA[]                        = "\xEE\x89\x81"; // U+E241 WF
    const constexpr char ICON_SAMOA[]                                    = "\xEE\x89\x8E"; // U+E24E WS
    const constexpr char ICON_KOSOVO[]                                   = "\xEE\x89\xA0"; // U+E260 XK
    const constexpr char ICON_YEMEN[]                                    = "\xEE\x89\xB4"; // U+E274 YE
    const constexpr char ICON_MAYOTTE[]                                  = "\xEE\x8A\x83"; // U+E283 YT
    const constexpr char ICON_SOUTH_AFRICA[]                             = "\xEE\x8A\x8A"; // U+E28A ZA
    const constexpr char ICON_ZAMBIA[]                                   = "\xEE\x8A\x96"; // U+E296 ZM
    const constexpr char ICON_ZIMBABWE[]                                 = "\xEE\x8A\xA0"; // U+E2A0 ZW
}
